import type { ToolDefinition } from '~/types/tool'

const localWebTool = {
  status: 'draft',
  requiresNetwork: false,
  localOnly: true,
  platforms: ['web'],
  capabilities: {},
} as const

export const TOOL_REGISTRY = [
  {
    ...localWebTool,
    status: 'enabled',
    id: 'timer',
    slug: 'timer',
    title: '计时器',
    description: '支持正计时、倒计时、暂停、继续、重置和到时提醒。',
    category: 'interactive',
    keywords: ['计时', '正计时', '倒计时', '秒表', 'countdown', 'stopwatch'],
  },
  {
    ...localWebTool,
    status: 'enabled',
    id: 'coin-flip',
    slug: 'coin-flip',
    title: '抛硬币',
    description: '随机生成正面或反面结果，支持连续重复操作。',
    category: 'interactive',
    keywords: ['硬币', '正反面', '随机', 'coin flip'],
  },
  {
    ...localWebTool,
    status: 'enabled',
    id: 'wheel',
    slug: 'wheel',
    title: '转盘',
    description: '编辑选项并启动转盘，快速得到一个随机结果。',
    category: 'interactive',
    keywords: ['转盘', '随机选择', '抽签', 'wheel', 'random picker'],
  },
  {
    ...localWebTool,
    status: 'enabled',
    id: 'dice',
    slug: 'dice',
    title: '掷骰子',
    description: '选择骰子数量并生成随机结果，适合游戏和现场决策。',
    category: 'interactive',
    keywords: ['骰子', '随机数', 'dice', 'roll'],
  },
  {
    ...localWebTool,
    status: 'enabled',
    id: 'marquee',
    slug: 'marquee',
    title: '手持弹幕',
    description: '设置文字、字号、颜色、背景和速度后全屏滚动展示。',
    category: 'interactive',
    keywords: ['手持弹幕', '弹幕', '滚动文字', '跑马灯', 'marquee'],
    capabilities: { fullscreen: true },
  },
  {
    ...localWebTool,
    status: 'enabled',
    id: 'metronome',
    slug: 'metronome',
    title: '节拍器',
    description: '在浏览器本地按设定 BPM 播放合成节拍，支持拍号和首拍重音。',
    category: 'interactive',
    keywords: ['节拍器', 'BPM', '节奏', '拍子', '重拍', 'metronome'],
    capabilities: { audio: true },
  },
  {
    ...localWebTool,
    status: 'enabled',
    id: 'prompter',
    slug: 'prompter',
    title: '提词器',
    description: '在浏览器本地滚动长篇稿件，支持阅读线、镜像和全屏舞台。',
    category: 'interactive',
    keywords: ['提词器', '滚动稿件', '演讲稿', '拍摄提纲', 'teleprompter', 'prompter'],
    capabilities: { fullscreen: true },
  },
  {
    ...localWebTool,
    status: 'enabled',
    id: 'date-time-calculator',
    slug: 'date-time-calculator',
    title: '日期时间计算器',
    description: '计算日期差，并在日期基础上增加或减少时间。',
    category: 'date-conversion',
    keywords: ['日期', '时间', '日期差', '时间差', '日期加减'],
  },
  {
    ...localWebTool,
    status: 'enabled',
    id: 'timestamp',
    slug: 'timestamp',
    title: '时间戳转换',
    description: '在秒级或毫秒级时间戳与 ISO 8601、本地时间、UTC 时间之间转换。',
    category: 'date-conversion',
    keywords: ['时间戳', 'Unix', 'Unix 时间', 'epoch', '秒级', '毫秒级'],
  },
  {
    ...localWebTool,
    status: 'enabled',
    id: 'world-time',
    slug: 'world-time',
    title: '世界时间',
    description: '浏览各国首都目录并查看当前世界时间，支持搜索添加和自定义 IANA 时区。',
    category: 'date-conversion',
    keywords: ['世界时间', '首都', '国家', '时区', 'IANA', 'UTC', '夏令时', 'world time', 'timezone'],
  },
  {
    ...localWebTool,
    status: 'enabled',
    id: 'base-converter',
    slug: 'base-converter',
    title: '进制转换',
    description: '在 2–36 自定义进制之间转换整数，支持大整数和常用前缀。',
    category: 'date-conversion',
    keywords: ['进制', '二进制', '八进制', '十进制', '十六进制', 'base conversion'],
  },
  {
    ...localWebTool,
    status: 'enabled',
    id: 'unit-converter',
    slug: 'unit-converter',
    title: '常用单位换算',
    description: '支持长度、面积、体积、质量、温度和速度等常用单位。',
    category: 'date-conversion',
    keywords: ['单位', '长度', '面积', '体积', '质量', '温度', '速度', '换算'],
  },
  {
    ...localWebTool,
    status: 'enabled',
    id: 'simplified-traditional',
    slug: 'simplified-traditional',
    title: '简繁体转换',
    description: '在简体中文和繁体中文之间进行文本转换。',
    category: 'date-conversion',
    keywords: ['简繁体', '简体', '繁体', '中文转换', '繁简转换'],
  },
  {
    ...localWebTool,
    status: 'enabled',
    id: 'number-to-chinese',
    slug: 'number-to-chinese',
    title: '数字与中文大写转换',
    description: '在普通数字、中文大写数字和金额表达之间转换。',
    category: 'date-conversion',
    keywords: ['中文大写', '大写数字', '金额大写', '数字转换'],
  },
  {
    ...localWebTool,
    status: 'enabled',
    id: 'json-workbench',
    slug: 'json-workbench',
    title: 'JSON 工作台',
    description: '在浏览器本地格式化、压缩、扁平化和反扁平化标准 JSON，支持多种缩进格式。',
    category: 'developer-text',
    keywords: [
      'JSON',
      'JSON 格式化',
      'JSON 压缩',
      'JSON 扁平化',
      'JSON 反扁平化',
      'json formatter',
      'json minifier',
      'json flatten',
      'json unflatten',
    ],
  },
  {
    ...localWebTool,
    status: 'enabled',
    id: 'json-to-sql',
    slug: 'json-to-sql',
    title: 'JSON 转 SQL',
    description: '在浏览器本地将扁平 JSON 对象数组转换为 MySQL 多行 INSERT 语句，支持复制和下载。',
    category: 'developer-text',
    keywords: ['JSON', 'SQL', 'MySQL', 'INSERT', '数据转换', '开发工具', 'json to sql'],
  },
  {
    ...localWebTool,
    status: 'enabled',
    id: 'url-tool',
    slug: 'url-tool',
    title: 'URL 工具',
    description: '解析并编辑 URL 查询参数，重建完整地址、生成 SQL 条件并进行编码或解码。',
    category: 'developer-text',
    keywords: ['URL', '网址', '链接', '编码', '解码', '查询参数', 'url parser'],
  },
  {
    ...localWebTool,
    status: 'enabled',
    id: 'character-count',
    slug: 'character-count',
    title: '字符统计',
    description: '统计含空格和不含空格的字符、词数、句子、段落、行数和字节。',
    category: 'developer-text',
    keywords: ['字符', '字数', '字节', '单词', '行数', '文本统计', 'character count'],
  },
  {
    ...localWebTool,
    status: 'enabled',
    id: 'uuid-generator',
    slug: 'uuid-generator',
    title: 'UUID 生成',
    description: '生成 1–100 个 UUID v4，支持大小写切换和逐行 TXT 导出。',
    category: 'developer-text',
    keywords: ['UUID', '唯一标识', 'uuid v4', 'guid'],
  },
  {
    ...localWebTool,
    status: 'enabled',
    id: 'password-generator',
    slug: 'password-generator',
    title: '密码生成器',
    description: '生成账号和安全随机密码，支持数量、长度、字符类型、前缀和后缀配置。',
    category: 'developer-text',
    keywords: ['密码', '随机密码', '安全密码', '账号密码', '用户名', 'password generator'],
  },
  {
    ...localWebTool,
    status: 'enabled',
    id: 'qr-code',
    slug: 'qr-code',
    title: '二维码生成',
    description: '输入文本或 URL，设置基本参数并导出二维码图片。',
    category: 'content-generation',
    keywords: ['二维码', 'QR Code', '链接二维码', 'qr generator'],
    capabilities: { canvas: true },
  },
  {
    ...localWebTool,
    status: 'enabled',
    id: 'barcode',
    slug: 'barcode',
    title: '条形码生成',
    description: '选择常用码制，校验输入并预览、导出条形码图片。',
    category: 'content-generation',
    keywords: ['条形码', 'barcode', '商品条码', 'barcode generator'],
    capabilities: { canvas: true },
  },
  {
    ...localWebTool,
    status: 'enabled',
    id: 'color-tool',
    slug: 'color-tool',
    title: '颜色工具',
    description: '输入、转换和复制常用色彩格式，并查看基础对比度提示。',
    category: 'content-generation',
    keywords: ['颜色', '取色', '调色', 'HEX', 'RGB', 'HSL', 'color converter'],
  },
  {
    ...localWebTool,
    id: 'morse-code',
    slug: 'morse-code',
    title: '摩斯码转换',
    description: '在文本与国际摩斯码之间进行本地双向转换。',
    category: 'developer-text',
    keywords: ['摩斯码', '摩斯电码', '电码', 'Morse', 'Morse code', '点划码'],
    status: 'enabled',
  },
  {
    ...localWebTool,
    status: 'enabled',
    id: 'shield-image',
    slug: 'shield-image',
    title: 'Shield 图片生成',
    description: '在浏览器本地生成双区域 Shield 图片，并支持 SVG 与 PNG 导出。',
    category: 'content-generation',
    keywords: ['Shield', '徽章', '状态徽章', '图片生成', 'SVG', 'PNG'],
    capabilities: { canvas: true },
  },
  {
    ...localWebTool,
    status: 'enabled',
    id: 'signature',
    slug: 'signature',
    title: '电子签名',
    description: '在浏览器本地绘制手写签名，并导出透明 PNG 图片。',
    category: 'content-generation',
    keywords: ['电子签名', '手写签名', '签名板', '透明 PNG', 'signature'],
    capabilities: { canvas: true },
  },
  {
    ...localWebTool,
    status: 'enabled',
    id: 'base64-image',
    slug: 'base64-image',
    title: 'Base64 图片转换',
    description: '在浏览器本地将 PNG、JPEG、WebP 或 GIF 图片与 Base64 文本互相转换。',
    category: 'content-generation',
    keywords: ['Base64', '图片转换', '图片编码', 'Data URL', 'image base64'],
    capabilities: { file: true },
  },
  {
    ...localWebTool,
    status: 'enabled',
    id: 'image-watermark',
    slug: 'image-watermark',
    title: '图片加水印',
    description: '在浏览器本地为 PNG、JPEG 或 WebP 图片叠加单条文本水印并下载。',
    category: 'content-generation',
    keywords: ['图片水印', '文字水印', '图片处理', 'PNG', 'JPEG', 'WebP', 'watermark'],
    capabilities: { file: true, canvas: true },
  },
 {
   ...localWebTool,
   status: 'enabled',
   id: 'ascii-art',
   slug: 'ascii-art',
   title: 'ASCII 画',
   description: '在浏览器本地将 PNG、JPEG 或 WebP 图片转换为可复制的 ASCII 字符画。',
   category: 'content-generation',
   keywords: ['ASCII 画', '字符画', '图片转字符', 'ASCII art', 'image to text'],
   capabilities: { file: true, canvas: true },
 },
  {
    ...localWebTool,
    status: 'enabled',
    id: 'torrent-magnet',
    slug: 'torrent-magnet',
    title: 'Torrent 分析 / Magnet',
    description: '在浏览器本地严格分析 v1 Torrent 文件并生成 Magnet 链接。',
    category: 'content-generation',
    keywords: ['Torrent', '种子分析', 'Magnet', '磁力链接', 'Bencode', 'btih'],
    capabilities: { file: true },
  },
] as const satisfies readonly ToolDefinition[]
