import type {
  HistoricalDatePrecision,
  HistoricalDynastyDatasetMetadata,
  HistoricalDynastyRecord,
  HistoricalDynastySource,
  HistoricalPeriodKey,
  HistoricalPeriodOption,
  HistoricalTrack,
} from './historical-dynasties'

export const HISTORICAL_PERIOD_OPTIONS: readonly HistoricalPeriodOption[] = [
  { value: 'pre-qin', label: '先秦', rangeLabel: '约前 2070 年—前 221 年' },
  { value: 'qin-han', label: '秦汉', rangeLabel: '前 221 年—220 年' },
  { value: 'six-dynasties', label: '三国两晋南北朝', rangeLabel: '220 年—589 年' },
  { value: 'sui-tang', label: '隋唐', rangeLabel: '581 年—907 年' },
  { value: 'five-song', label: '五代宋辽金夏', rangeLabel: '907 年—1279 年' },
  { value: 'yuan-ming-qing', label: '元明清', rangeLabel: '1271 年—1912 年' },
]

const HISTORICAL_DYNASTY_SOURCE_LIST: readonly HistoricalDynastySource[] = [
  {
    id: 'ihns-year-index',
    name: '中国科学院自然科学史研究所：中国历代年号索引表',
    url: 'https://agri-history.ihns.ac.cn/history/historic%20table.htm',
    scope: '用于年号、朝代段落及公元前/后年份的交叉核对；页面年代较早，不单独作为争议年份的唯一依据。',
  },
  {
    id: 'cssn-chronology',
    name: '中国社会科学网：《中国历史纪年表》检索记录',
    url: 'https://www.cssn.cn/was5/web/search?channelid=252048&outlinepage=10&page=150&perpage=10',
    scope: '用于历史年表覆盖范围和并行年表章节的来源线索，具体记录仍需结合学术资料复核。',
  },
]

type HistoricalDynastySeed = {
  readonly id: string
  readonly nameZh: string
  readonly aliases: readonly string[]
  readonly startYear: number
  readonly endYear: number
  readonly startLabel: string
  readonly endLabel: string
  readonly datePrecision: HistoricalDatePrecision
  readonly periodKey: HistoricalPeriodKey
  readonly track: HistoricalTrack
  readonly note: string
}

const HISTORICAL_DYNASTY_SEEDS: readonly HistoricalDynastySeed[] = [
  {
    id: 'xia',
    nameZh: '夏',
    aliases: ['夏朝'],
    startYear: -2070,
    endYear: -1600,
    startLabel: '约前2070年',
    endLabel: '约前1600年',
    datePrecision: 'approximate',
    periodKey: 'pre-qin',
    track: 'mainline',
    note: '传统纪年，起止年份存在不同学术方案；首版只作时间轴概览。',
  },
  {
    id: 'shang',
    nameZh: '商',
    aliases: ['商朝', '殷商'],
    startYear: -1600,
    endYear: -1046,
    startLabel: '约前1600年',
    endLabel: '前1046年',
    datePrecision: 'approximate',
    periodKey: 'pre-qin',
    track: 'mainline',
    note: '早期起始年代采用常见概略口径；具体年代不展开为逐年年表。',
  },
  {
    id: 'western-zhou',
    nameZh: '西周',
    aliases: ['周朝', '西周王朝'],
    startYear: -1046,
    endYear: -771,
    startLabel: '前1046年',
    endLabel: '前771年',
    datePrecision: 'exact',
    periodKey: 'pre-qin',
    track: 'mainline',
    note: '以通行的武王克商至镐京失守年代表示。',
  },
  {
    id: 'eastern-zhou',
    nameZh: '东周',
    aliases: ['东周王朝', '春秋战国'],
    startYear: -770,
    endYear: -256,
    startLabel: '前770年',
    endLabel: '前256年',
    datePrecision: 'exact',
    periodKey: 'pre-qin',
    track: 'mainline',
    note: '周王室东迁后的王朝阶段；春秋战国诸侯另列为并行政权轨道。',
  },
  {
    id: 'qin',
    nameZh: '秦',
    aliases: ['秦朝'],
    startYear: -221,
    endYear: -206,
    startLabel: '前221年',
    endLabel: '前206年',
    datePrecision: 'exact',
    periodKey: 'qin-han',
    track: 'mainline',
    note: '以秦统一六国至秦亡的通行年代表示。',
  },
  {
    id: 'western-han',
    nameZh: '西汉',
    aliases: ['汉朝', '前汉'],
    startYear: -202,
    endYear: 9,
    startLabel: '前202年',
    endLabel: '9年',
    datePrecision: 'exact',
    periodKey: 'qin-han',
    track: 'mainline',
    note: '中间的新朝作为独立记录显示，不压缩为连续一条汉朝卡片。',
  },
  {
    id: 'xin',
    nameZh: '新',
    aliases: ['新朝', '王莽新朝'],
    startYear: 9,
    endYear: 23,
    startLabel: '9年',
    endLabel: '23年',
    datePrecision: 'exact',
    periodKey: 'qin-han',
    track: 'mainline',
    note: '位于西汉与东汉之间的短期王朝记录。',
  },
  {
    id: 'eastern-han',
    nameZh: '东汉',
    aliases: ['后汉', '东汉王朝'],
    startYear: 25,
    endYear: 220,
    startLabel: '25年',
    endLabel: '220年',
    datePrecision: 'exact',
    periodKey: 'qin-han',
    track: 'mainline',
    note: '以光武帝建武元年至汉献帝禅让前的通行年代表示。',
  },
  {
    id: 'western-jin',
    nameZh: '西晋',
    aliases: ['晋朝', '西晋王朝'],
    startYear: 266,
    endYear: 316,
    startLabel: '266年',
    endLabel: '316年',
    datePrecision: 'exact',
    periodKey: 'six-dynasties',
    track: 'mainline',
    note: '三国结束后短暂统一的晋朝前期。',
  },
  {
    id: 'eastern-jin',
    nameZh: '东晋',
    aliases: ['东晋王朝'],
    startYear: 317,
    endYear: 420,
    startLabel: '317年',
    endLabel: '420年',
    datePrecision: 'exact',
    periodKey: 'six-dynasties',
    track: 'mainline',
    note: '东晋与北方十六国并存，北方政权以并行聚合记录表示。',
  },
  {
    id: 'sui',
    nameZh: '隋',
    aliases: ['隋朝'],
    startYear: 581,
    endYear: 618,
    startLabel: '581年',
    endLabel: '618年',
    datePrecision: 'exact',
    periodKey: 'sui-tang',
    track: 'mainline',
    note: '南北朝之后重新完成大范围统一的王朝。',
  },
  {
    id: 'tang',
    nameZh: '唐',
    aliases: ['唐朝'],
    startYear: 618,
    endYear: 907,
    startLabel: '618年',
    endLabel: '907年',
    datePrecision: 'exact',
    periodKey: 'sui-tang',
    track: 'mainline',
    note: '唐朝后期的藩镇与地方政权不在首版逐一展开。',
  },
  {
    id: 'later-liang',
    nameZh: '后梁',
    aliases: ['五代后梁'],
    startYear: 907,
    endYear: 923,
    startLabel: '907年',
    endLabel: '923年',
    datePrecision: 'exact',
    periodKey: 'five-song',
    track: 'mainline',
    note: '五代主线之一；十国诸政权以并行聚合记录表示。',
  },
  {
    id: 'later-tang',
    nameZh: '后唐',
    aliases: ['五代后唐'],
    startYear: 923,
    endYear: 936,
    startLabel: '923年',
    endLabel: '936年',
    datePrecision: 'exact',
    periodKey: 'five-song',
    track: 'mainline',
    note: '五代主线之一。',
  },
  {
    id: 'later-jin',
    nameZh: '后晋',
    aliases: ['五代后晋'],
    startYear: 936,
    endYear: 947,
    startLabel: '936年',
    endLabel: '947年',
    datePrecision: 'exact',
    periodKey: 'five-song',
    track: 'mainline',
    note: '五代主线之一。',
  },
  {
    id: 'later-han',
    nameZh: '后汉',
    aliases: ['五代后汉'],
    startYear: 947,
    endYear: 951,
    startLabel: '947年',
    endLabel: '951年',
    datePrecision: 'exact',
    periodKey: 'five-song',
    track: 'mainline',
    note: '五代主线之一，与东汉名称相同但阶段标签不同。',
  },
  {
    id: 'later-zhou',
    nameZh: '后周',
    aliases: ['五代后周'],
    startYear: 951,
    endYear: 960,
    startLabel: '951年',
    endLabel: '960年',
    datePrecision: 'exact',
    periodKey: 'five-song',
    track: 'mainline',
    note: '五代最后一个王朝。',
  },
  {
    id: 'northern-song',
    nameZh: '北宋',
    aliases: ['宋朝', '北宋王朝'],
    startYear: 960,
    endYear: 1127,
    startLabel: '960年',
    endLabel: '1127年',
    datePrecision: 'exact',
    periodKey: 'five-song',
    track: 'mainline',
    note: '与辽、西夏并存；相关政权在并行轨道展示。',
  },
  {
    id: 'southern-song',
    nameZh: '南宋',
    aliases: ['南宋王朝'],
    startYear: 1127,
    endYear: 1279,
    startLabel: '1127年',
    endLabel: '1279年',
    datePrecision: 'exact',
    periodKey: 'five-song',
    track: 'mainline',
    note: '南宋与金、西夏及后期元朝存在阶段性并存。',
  },
  {
    id: 'yuan',
    nameZh: '元',
    aliases: ['元朝', '大元'],
    startYear: 1271,
    endYear: 1368,
    startLabel: '1271年',
    endLabel: '1368年',
    datePrecision: 'exact',
    periodKey: 'yuan-ming-qing',
    track: 'mainline',
    note: '以国号定为“大元”的1271年作为起点，统一与政权沿革另有口径。',
  },
  {
    id: 'ming',
    nameZh: '明',
    aliases: ['明朝', '大明'],
    startYear: 1368,
    endYear: 1644,
    startLabel: '1368年',
    endLabel: '1644年',
    datePrecision: 'exact',
    periodKey: 'yuan-ming-qing',
    track: 'mainline',
    note: '明朝灭亡后的南明以并行记录表示，不合并为同一张主线卡片。',
  },
  {
    id: 'qing',
    nameZh: '清',
    aliases: ['清朝', '大清'],
    startYear: 1636,
    endYear: 1912,
    startLabel: '1636年（国号定为清）',
    endLabel: '1912年（清帝退位）',
    datePrecision: 'range',
    periodKey: 'yuan-ming-qing',
    track: 'mainline',
    note: '起点采用1636年国号口径；1644年入关作为重要节点在说明中保留，不伪装为唯一无争议起点。',
  },
  {
    id: 'warring-states',
    nameZh: '战国诸侯',
    aliases: ['战国七雄', '诸侯国'],
    startYear: -475,
    endYear: -221,
    startLabel: '约前475年',
    endLabel: '前221年',
    datePrecision: 'traditional',
    periodKey: 'pre-qin',
    track: 'parallel',
    note: '以齐、楚、燕、韩、赵、魏等主要诸侯并立作聚合展示，不展开完整诸侯年表。',
  },
  {
    id: 'sixteen-states',
    nameZh: '十六国诸政权',
    aliases: ['十六国', '五胡十六国'],
    startYear: 304,
    endYear: 439,
    startLabel: '304年',
    endLabel: '439年',
    datePrecision: 'range',
    periodKey: 'six-dynasties',
    track: 'parallel',
    note: '北方多个政权并存的聚合记录；不在首版逐一展示全部短期政权。',
  },
  {
    id: 'cao-wei',
    nameZh: '曹魏',
    aliases: ['魏', '魏国'],
    startYear: 220,
    endYear: 265,
    startLabel: '220年',
    endLabel: '265年',
    datePrecision: 'exact',
    periodKey: 'six-dynasties',
    track: 'parallel',
    note: '三国时期政权之一，与蜀汉、东吴并行展示。',
  },
  {
    id: 'shu-han',
    nameZh: '蜀汉',
    aliases: ['蜀', '汉'],
    startYear: 221,
    endYear: 263,
    startLabel: '221年',
    endLabel: '263年',
    datePrecision: 'exact',
    periodKey: 'six-dynasties',
    track: 'parallel',
    note: '三国时期政权之一，与曹魏、东吴并行展示。',
  },
  {
    id: 'eastern-wu',
    nameZh: '东吴',
    aliases: ['吴', '吴国'],
    startYear: 222,
    endYear: 280,
    startLabel: '222年',
    endLabel: '280年',
    datePrecision: 'exact',
    periodKey: 'six-dynasties',
    track: 'parallel',
    note: '三国时期政权之一，与曹魏、蜀汉并行展示。',
  },
  {
    id: 'northern-wei',
    nameZh: '北魏',
    aliases: ['拓跋魏'],
    startYear: 386,
    endYear: 534,
    startLabel: '386年',
    endLabel: '534年',
    datePrecision: 'exact',
    periodKey: 'six-dynasties',
    track: 'parallel',
    note: '北朝主要政权之一，后分为东魏与西魏。',
  },
  {
    id: 'liu-song',
    nameZh: '刘宋',
    aliases: ['南朝宋', '宋'],
    startYear: 420,
    endYear: 479,
    startLabel: '420年',
    endLabel: '479年',
    datePrecision: 'exact',
    periodKey: 'six-dynasties',
    track: 'parallel',
    note: '南朝第一个主要政权，使用“刘宋”以区别于北宋和南宋。',
  },
  {
    id: 'southern-qi',
    nameZh: '南齐',
    aliases: ['南朝齐', '齐'],
    startYear: 479,
    endYear: 502,
    startLabel: '479年',
    endLabel: '502年',
    datePrecision: 'exact',
    periodKey: 'six-dynasties',
    track: 'parallel',
    note: '南朝主要政权之一。',
  },
  {
    id: 'liang',
    nameZh: '梁',
    aliases: ['南梁', '南朝梁'],
    startYear: 502,
    endYear: 557,
    startLabel: '502年',
    endLabel: '557年',
    datePrecision: 'exact',
    periodKey: 'six-dynasties',
    track: 'parallel',
    note: '南朝主要政权之一。',
  },
  {
    id: 'chen',
    nameZh: '陈',
    aliases: ['南陈', '南朝陈'],
    startYear: 557,
    endYear: 589,
    startLabel: '557年',
    endLabel: '589年',
    datePrecision: 'exact',
    periodKey: 'six-dynasties',
    track: 'parallel',
    note: '南朝最后一个主要政权。',
  },
  {
    id: 'eastern-wei',
    nameZh: '东魏',
    aliases: ['东魏王朝'],
    startYear: 534,
    endYear: 550,
    startLabel: '534年',
    endLabel: '550年',
    datePrecision: 'exact',
    periodKey: 'six-dynasties',
    track: 'parallel',
    note: '北魏分裂后的北朝政权之一。',
  },
  {
    id: 'western-wei',
    nameZh: '西魏',
    aliases: ['西魏王朝'],
    startYear: 535,
    endYear: 557,
    startLabel: '535年',
    endLabel: '557年',
    datePrecision: 'exact',
    periodKey: 'six-dynasties',
    track: 'parallel',
    note: '北魏分裂后的北朝政权之一。',
  },
  {
    id: 'northern-qi',
    nameZh: '北齐',
    aliases: ['北齐王朝'],
    startYear: 550,
    endYear: 577,
    startLabel: '550年',
    endLabel: '577年',
    datePrecision: 'exact',
    periodKey: 'six-dynasties',
    track: 'parallel',
    note: '东魏之后的北朝政权之一。',
  },
  {
    id: 'northern-zhou',
    nameZh: '北周',
    aliases: ['北周王朝'],
    startYear: 557,
    endYear: 581,
    startLabel: '557年',
    endLabel: '581年',
    datePrecision: 'exact',
    periodKey: 'six-dynasties',
    track: 'parallel',
    note: '西魏之后的北朝政权，后为隋所代。',
  },
  {
    id: 'dali',
    nameZh: '大理',
    aliases: ['大理国'],
    startYear: 937,
    endYear: 1253,
    startLabel: '937年',
    endLabel: '1253年',
    datePrecision: 'range',
    periodKey: 'five-song',
    track: 'parallel',
    note: '西南地区的重要政权，作为区域并行记录展示，不等同于中原主线朝代。',
  },
  {
    id: 'ten-kingdoms',
    nameZh: '十国诸政权',
    aliases: ['十国', '五代十国'],
    startYear: 902,
    endYear: 979,
    startLabel: '902年',
    endLabel: '979年',
    datePrecision: 'range',
    periodKey: 'five-song',
    track: 'parallel',
    note: '五代时期南方及其他地区多个政权的聚合记录，不逐一展开。',
  },
  {
    id: 'liao',
    nameZh: '辽',
    aliases: ['辽朝', '契丹'],
    startYear: 916,
    endYear: 1125,
    startLabel: '916年',
    endLabel: '1125年',
    datePrecision: 'exact',
    periodKey: 'five-song',
    track: 'parallel',
    note: '与北宋长期并存的北方政权。',
  },
  {
    id: 'western-xia',
    nameZh: '西夏',
    aliases: ['西夏王朝', '党项'],
    startYear: 1038,
    endYear: 1227,
    startLabel: '1038年',
    endLabel: '1227年',
    datePrecision: 'exact',
    periodKey: 'five-song',
    track: 'parallel',
    note: '与北宋、南宋及金存在阶段性并存的西北政权。',
  },
  {
    id: 'jin',
    nameZh: '金',
    aliases: ['金朝', '女真金'],
    startYear: 1115,
    endYear: 1234,
    startLabel: '1115年',
    endLabel: '1234年',
    datePrecision: 'exact',
    periodKey: 'five-song',
    track: 'parallel',
    note: '与南宋及西夏存在阶段性并存；名称在页面中以阶段标签区分。',
  },
  {
    id: 'northern-yuan',
    nameZh: '北元',
    aliases: ['北元政权'],
    startYear: 1368,
    endYear: 1388,
    startLabel: '1368年',
    endLabel: '1388年前后',
    datePrecision: 'range',
    periodKey: 'yuan-ming-qing',
    track: 'parallel',
    note: '元朝退出中原后的蒙古政权称谓，起止口径存在差异，首版以范围说明保留。',
  },
  {
    id: 'southern-ming',
    nameZh: '南明',
    aliases: ['南明政权'],
    startYear: 1644,
    endYear: 1662,
    startLabel: '1644年起',
    endLabel: '1662年前后',
    datePrecision: 'range',
    periodKey: 'yuan-ming-qing',
    track: 'parallel',
    note: '明朝在南方延续的多个政权聚合记录，起止以阶段范围表示，不展开逐帝列表。',
  },
]

export const HISTORICAL_DYNASTY_CATALOG: readonly HistoricalDynastyRecord[] = HISTORICAL_DYNASTY_SEEDS.map((seed) => ({
  ...seed,
  sourceRefs: ['ihns-year-index', 'cssn-chronology'],
}))

const HISTORICAL_MAINLINE_COUNT = HISTORICAL_DYNASTY_CATALOG.filter((record) => record.track === 'mainline').length
const HISTORICAL_PARALLEL_COUNT = HISTORICAL_DYNASTY_CATALOG.filter((record) => record.track === 'parallel').length

/** 历史朝代表数据集的版本、来源和覆盖边界。 */
export const HISTORICAL_DYNASTY_DATASET_METADATA: HistoricalDynastyDatasetMetadata = {
  id: 'historical-dynasties',
  name: '中国古代主要朝代与并行政权时间轴',
  version: 'ihns-cssn-reviewed-20260918',
  checkedAt: '2026-09-18',
  coverage: '首版覆盖夏、商、周至清的主要主线朝代，并以聚合或主要记录展示三国、十六国、南北朝、五代十国、辽、西夏、金、大理、北元和南明等并行关系；不覆盖现代中国历史、逐帝目录、疆域地图或完整地方政权表。',
  validation: `目录包含 ${HISTORICAL_DYNASTY_CATALOG.length} 条记录，其中主线 ${HISTORICAL_MAINLINE_COUNT} 条、并行政权 ${HISTORICAL_PARALLEL_COUNT} 条；约略年代、区间和传统纪年均保留精度标记，争议记录以说明文本限定适用范围。`,
  recordCount: HISTORICAL_DYNASTY_CATALOG.length,
  mainlineCount: HISTORICAL_MAINLINE_COUNT,
  parallelCount: HISTORICAL_PARALLEL_COUNT,
  sources: HISTORICAL_DYNASTY_SOURCE_LIST,
}
