import { WORLD_TIME_BUILTIN_OPTIONS } from './world-time-catalog'
import type {
  CapitalRole,
  CountryCapitalRecord,
  WorldCapitalDatasetMetadata,
} from './world-capitals'

interface CountryIsoCode {
  readonly alpha2: string
  readonly alpha3: string
}

const COUNTRY_ISO_CODES: Readonly<Record<string, CountryIsoCode>> = {
  Afghanistan: { alpha2: 'AF', alpha3: 'AFG' },
  Albania: { alpha2: 'AL', alpha3: 'ALB' },
  Algeria: { alpha2: 'DZ', alpha3: 'DZA' },
  Andorra: { alpha2: 'AD', alpha3: 'AND' },
  Angola: { alpha2: 'AO', alpha3: 'AGO' },
  'Antigua and Barbuda': { alpha2: 'AG', alpha3: 'ATG' },
  Argentina: { alpha2: 'AR', alpha3: 'ARG' },
  Armenia: { alpha2: 'AM', alpha3: 'ARM' },
  Australia: { alpha2: 'AU', alpha3: 'AUS' },
  Austria: { alpha2: 'AT', alpha3: 'AUT' },
  Azerbaijan: { alpha2: 'AZ', alpha3: 'AZE' },
  Bahamas: { alpha2: 'BS', alpha3: 'BHS' },
  Bahrain: { alpha2: 'BH', alpha3: 'BHR' },
  Bangladesh: { alpha2: 'BD', alpha3: 'BGD' },
  Barbados: { alpha2: 'BB', alpha3: 'BRB' },
  Belarus: { alpha2: 'BY', alpha3: 'BLR' },
  Belgium: { alpha2: 'BE', alpha3: 'BEL' },
  Belize: { alpha2: 'BZ', alpha3: 'BLZ' },
  Benin: { alpha2: 'BJ', alpha3: 'BEN' },
  Bhutan: { alpha2: 'BT', alpha3: 'BTN' },
  Bolivia: { alpha2: 'BO', alpha3: 'BOL' },
  'Bosnia and Herzegovina': { alpha2: 'BA', alpha3: 'BIH' },
  Botswana: { alpha2: 'BW', alpha3: 'BWA' },
  Brazil: { alpha2: 'BR', alpha3: 'BRA' },
  Brunei: { alpha2: 'BN', alpha3: 'BRN' },
  Bulgaria: { alpha2: 'BG', alpha3: 'BGR' },
  'Burkina Faso': { alpha2: 'BF', alpha3: 'BFA' },
  Burundi: { alpha2: 'BI', alpha3: 'BDI' },
  'Cabo Verde': { alpha2: 'CV', alpha3: 'CPV' },
  Cambodia: { alpha2: 'KH', alpha3: 'KHM' },
  Cameroon: { alpha2: 'CM', alpha3: 'CMR' },
  Canada: { alpha2: 'CA', alpha3: 'CAN' },
  'Central African Republic': { alpha2: 'CF', alpha3: 'CAF' },
  Chad: { alpha2: 'TD', alpha3: 'TCD' },
  Chile: { alpha2: 'CL', alpha3: 'CHL' },
  China: { alpha2: 'CN', alpha3: 'CHN' },
  Colombia: { alpha2: 'CO', alpha3: 'COL' },
  Comoros: { alpha2: 'KM', alpha3: 'COM' },
  'Costa Rica': { alpha2: 'CR', alpha3: 'CRI' },
  "Cote d'Ivoire": { alpha2: 'CI', alpha3: 'CIV' },
  Croatia: { alpha2: 'HR', alpha3: 'HRV' },
  Cuba: { alpha2: 'CU', alpha3: 'CUB' },
  Cyprus: { alpha2: 'CY', alpha3: 'CYP' },
  Czechia: { alpha2: 'CZ', alpha3: 'CZE' },
  'Democratic Republic of the Congo': { alpha2: 'CD', alpha3: 'COD' },
  Denmark: { alpha2: 'DK', alpha3: 'DNK' },
  Djibouti: { alpha2: 'DJ', alpha3: 'DJI' },
  Dominica: { alpha2: 'DM', alpha3: 'DMA' },
  'Dominican Republic': { alpha2: 'DO', alpha3: 'DOM' },
  Ecuador: { alpha2: 'EC', alpha3: 'ECU' },
  Egypt: { alpha2: 'EG', alpha3: 'EGY' },
  'El Salvador': { alpha2: 'SV', alpha3: 'SLV' },
  'Equatorial Guinea': { alpha2: 'GQ', alpha3: 'GNQ' },
  Eritrea: { alpha2: 'ER', alpha3: 'ERI' },
  Estonia: { alpha2: 'EE', alpha3: 'EST' },
  Eswatini: { alpha2: 'SZ', alpha3: 'SWZ' },
  Ethiopia: { alpha2: 'ET', alpha3: 'ETH' },
  Fiji: { alpha2: 'FJ', alpha3: 'FJI' },
  Finland: { alpha2: 'FI', alpha3: 'FIN' },
  France: { alpha2: 'FR', alpha3: 'FRA' },
  Gabon: { alpha2: 'GA', alpha3: 'GAB' },
  Gambia: { alpha2: 'GM', alpha3: 'GMB' },
  Georgia: { alpha2: 'GE', alpha3: 'GEO' },
  Germany: { alpha2: 'DE', alpha3: 'DEU' },
  Ghana: { alpha2: 'GH', alpha3: 'GHA' },
  Greece: { alpha2: 'GR', alpha3: 'GRC' },
  Grenada: { alpha2: 'GD', alpha3: 'GRD' },
  Guatemala: { alpha2: 'GT', alpha3: 'GTM' },
  Guinea: { alpha2: 'GN', alpha3: 'GIN' },
  'Guinea-Bissau': { alpha2: 'GW', alpha3: 'GNB' },
  Guyana: { alpha2: 'GY', alpha3: 'GUY' },
  Haiti: { alpha2: 'HT', alpha3: 'HTI' },
  'Holy See': { alpha2: 'VA', alpha3: 'VAT' },
  Honduras: { alpha2: 'HN', alpha3: 'HND' },
  Hungary: { alpha2: 'HU', alpha3: 'HUN' },
  Iceland: { alpha2: 'IS', alpha3: 'ISL' },
  India: { alpha2: 'IN', alpha3: 'IND' },
  Indonesia: { alpha2: 'ID', alpha3: 'IDN' },
  Iran: { alpha2: 'IR', alpha3: 'IRN' },
  Iraq: { alpha2: 'IQ', alpha3: 'IRQ' },
  Ireland: { alpha2: 'IE', alpha3: 'IRL' },
  Israel: { alpha2: 'IL', alpha3: 'ISR' },
  Italy: { alpha2: 'IT', alpha3: 'ITA' },
  Jamaica: { alpha2: 'JM', alpha3: 'JAM' },
  Japan: { alpha2: 'JP', alpha3: 'JPN' },
  Jordan: { alpha2: 'JO', alpha3: 'JOR' },
  Kazakhstan: { alpha2: 'KZ', alpha3: 'KAZ' },
  Kenya: { alpha2: 'KE', alpha3: 'KEN' },
  Kiribati: { alpha2: 'KI', alpha3: 'KIR' },
  Kuwait: { alpha2: 'KW', alpha3: 'KWT' },
  Kyrgyzstan: { alpha2: 'KG', alpha3: 'KGZ' },
  Laos: { alpha2: 'LA', alpha3: 'LAO' },
  Latvia: { alpha2: 'LV', alpha3: 'LVA' },
  Lebanon: { alpha2: 'LB', alpha3: 'LBN' },
  Lesotho: { alpha2: 'LS', alpha3: 'LSO' },
  Liberia: { alpha2: 'LR', alpha3: 'LBR' },
  Libya: { alpha2: 'LY', alpha3: 'LBY' },
  Liechtenstein: { alpha2: 'LI', alpha3: 'LIE' },
  Lithuania: { alpha2: 'LT', alpha3: 'LTU' },
  Luxembourg: { alpha2: 'LU', alpha3: 'LUX' },
  Madagascar: { alpha2: 'MG', alpha3: 'MDG' },
  Malawi: { alpha2: 'MW', alpha3: 'MWI' },
  Malaysia: { alpha2: 'MY', alpha3: 'MYS' },
  Maldives: { alpha2: 'MV', alpha3: 'MDV' },
  Mali: { alpha2: 'ML', alpha3: 'MLI' },
  Malta: { alpha2: 'MT', alpha3: 'MLT' },
  'Marshall Islands': { alpha2: 'MH', alpha3: 'MHL' },
  Mauritania: { alpha2: 'MR', alpha3: 'MRT' },
  Mauritius: { alpha2: 'MU', alpha3: 'MUS' },
  Mexico: { alpha2: 'MX', alpha3: 'MEX' },
  Micronesia: { alpha2: 'FM', alpha3: 'FSM' },
  Moldova: { alpha2: 'MD', alpha3: 'MDA' },
  Monaco: { alpha2: 'MC', alpha3: 'MCO' },
  Mongolia: { alpha2: 'MN', alpha3: 'MNG' },
  Montenegro: { alpha2: 'ME', alpha3: 'MNE' },
  Morocco: { alpha2: 'MA', alpha3: 'MAR' },
  Mozambique: { alpha2: 'MZ', alpha3: 'MOZ' },
  Myanmar: { alpha2: 'MM', alpha3: 'MMR' },
  Namibia: { alpha2: 'NA', alpha3: 'NAM' },
  Nauru: { alpha2: 'NR', alpha3: 'NRU' },
  Nepal: { alpha2: 'NP', alpha3: 'NPL' },
  Netherlands: { alpha2: 'NL', alpha3: 'NLD' },
  'New Zealand': { alpha2: 'NZ', alpha3: 'NZL' },
  Nicaragua: { alpha2: 'NI', alpha3: 'NIC' },
  Niger: { alpha2: 'NE', alpha3: 'NER' },
  Nigeria: { alpha2: 'NG', alpha3: 'NGA' },
  'North Korea': { alpha2: 'KP', alpha3: 'PRK' },
  'North Macedonia': { alpha2: 'MK', alpha3: 'MKD' },
  Norway: { alpha2: 'NO', alpha3: 'NOR' },
  Oman: { alpha2: 'OM', alpha3: 'OMN' },
  Pakistan: { alpha2: 'PK', alpha3: 'PAK' },
  Palau: { alpha2: 'PW', alpha3: 'PLW' },
  Panama: { alpha2: 'PA', alpha3: 'PAN' },
  'Papua New Guinea': { alpha2: 'PG', alpha3: 'PNG' },
  Paraguay: { alpha2: 'PY', alpha3: 'PRY' },
  Peru: { alpha2: 'PE', alpha3: 'PER' },
  Philippines: { alpha2: 'PH', alpha3: 'PHL' },
  Poland: { alpha2: 'PL', alpha3: 'POL' },
  Portugal: { alpha2: 'PT', alpha3: 'PRT' },
  Qatar: { alpha2: 'QA', alpha3: 'QAT' },
  'Republic of the Congo': { alpha2: 'CG', alpha3: 'COG' },
  Romania: { alpha2: 'RO', alpha3: 'ROU' },
  Russia: { alpha2: 'RU', alpha3: 'RUS' },
  Rwanda: { alpha2: 'RW', alpha3: 'RWA' },
  'Saint Kitts and Nevis': { alpha2: 'KN', alpha3: 'KNA' },
  'Saint Lucia': { alpha2: 'LC', alpha3: 'LCA' },
  'Saint Vincent and the Grenadines': { alpha2: 'VC', alpha3: 'VCT' },
  Samoa: { alpha2: 'WS', alpha3: 'WSM' },
  'San Marino': { alpha2: 'SM', alpha3: 'SMR' },
  'Sao Tome and Principe': { alpha2: 'ST', alpha3: 'STP' },
  'Saudi Arabia': { alpha2: 'SA', alpha3: 'SAU' },
  Senegal: { alpha2: 'SN', alpha3: 'SEN' },
  Serbia: { alpha2: 'RS', alpha3: 'SRB' },
  Seychelles: { alpha2: 'SC', alpha3: 'SYC' },
  'Sierra Leone': { alpha2: 'SL', alpha3: 'SLE' },
  Singapore: { alpha2: 'SG', alpha3: 'SGP' },
  Slovakia: { alpha2: 'SK', alpha3: 'SVK' },
  Slovenia: { alpha2: 'SI', alpha3: 'SVN' },
  'Solomon Islands': { alpha2: 'SB', alpha3: 'SLB' },
  Somalia: { alpha2: 'SO', alpha3: 'SOM' },
  'South Africa': { alpha2: 'ZA', alpha3: 'ZAF' },
  'South Korea': { alpha2: 'KR', alpha3: 'KOR' },
  'South Sudan': { alpha2: 'SS', alpha3: 'SSD' },
  Spain: { alpha2: 'ES', alpha3: 'ESP' },
  'Sri Lanka': { alpha2: 'LK', alpha3: 'LKA' },
  'State of Palestine': { alpha2: 'PS', alpha3: 'PSE' },
  Sudan: { alpha2: 'SD', alpha3: 'SDN' },
  Suriname: { alpha2: 'SR', alpha3: 'SUR' },
  Sweden: { alpha2: 'SE', alpha3: 'SWE' },
  Switzerland: { alpha2: 'CH', alpha3: 'CHE' },
  Syria: { alpha2: 'SY', alpha3: 'SYR' },
  Tajikistan: { alpha2: 'TJ', alpha3: 'TJK' },
  Tanzania: { alpha2: 'TZ', alpha3: 'TZA' },
  Thailand: { alpha2: 'TH', alpha3: 'THA' },
  'Timor-Leste': { alpha2: 'TL', alpha3: 'TLS' },
  Togo: { alpha2: 'TG', alpha3: 'TGO' },
  Tonga: { alpha2: 'TO', alpha3: 'TON' },
  'Trinidad and Tobago': { alpha2: 'TT', alpha3: 'TTO' },
  Tunisia: { alpha2: 'TN', alpha3: 'TUN' },
  Turkey: { alpha2: 'TR', alpha3: 'TUR' },
  Turkmenistan: { alpha2: 'TM', alpha3: 'TKM' },
  Tuvalu: { alpha2: 'TV', alpha3: 'TUV' },
  Uganda: { alpha2: 'UG', alpha3: 'UGA' },
  Ukraine: { alpha2: 'UA', alpha3: 'UKR' },
  'United Arab Emirates': { alpha2: 'AE', alpha3: 'ARE' },
  'United Kingdom': { alpha2: 'GB', alpha3: 'GBR' },
  'United States': { alpha2: 'US', alpha3: 'USA' },
  Uruguay: { alpha2: 'UY', alpha3: 'URY' },
  Uzbekistan: { alpha2: 'UZ', alpha3: 'UZB' },
  Vanuatu: { alpha2: 'VU', alpha3: 'VUT' },
  Venezuela: { alpha2: 'VE', alpha3: 'VEN' },
  Vietnam: { alpha2: 'VN', alpha3: 'VNM' },
  Yemen: { alpha2: 'YE', alpha3: 'YEM' },
  Zambia: { alpha2: 'ZM', alpha3: 'ZMB' },
  Zimbabwe: { alpha2: 'ZW', alpha3: 'ZWE' },
}

const COUNTRY_ALIASES_BY_ALPHA3: Readonly<Record<string, readonly string[]>> = {
  AFG: ['Islamic Republic of Afghanistan'],
  BOL: ['Plurinational State of Bolivia'],
  BRN: ['Brunei Darussalam'],
  CIV: ["Côte d'Ivoire", 'Ivory Coast'],
  COD: ['DR Congo', 'DRC'],
  COG: ['Congo', 'Republic of Congo'],
  CPV: ['Cape Verde'],
  CZE: ['Czech Republic'],
  FSM: ['Federated States of Micronesia'],
  GBR: ['UK', 'U.K.', 'Great Britain', 'Britain'],
  IRN: ['Islamic Republic of Iran'],
  KOR: ['Republic of Korea'],
  LAO: ["Lao People's Democratic Republic"],
  MDA: ['Republic of Moldova'],
  MKD: ['Macedonia'],
  MMR: ['Burma'],
  PRK: ['DPRK', "Democratic People's Republic of Korea"],
  PSE: ['Palestine'],
  RUS: ['Russian Federation'],
  SWZ: ['Swaziland'],
  TLS: ['East Timor'],
  TUR: ['Türkiye'],
  TZA: ['United Republic of Tanzania'],
  USA: ['United States of America', 'US', 'USA', 'America'],
  VEN: ['Bolivarian Republic of Venezuela'],
  VAT: ['Vatican City', 'Vatican'],
  VNM: ['Viet Nam'],
}

const CAPITAL_ALIASES_BY_ID: Readonly<Record<string, readonly string[]>> = {
  'china-beijing': ['Peking'],
  'holy-see-vatican-city': ['Vatican', 'Vatican City'],
  'myanmar-naypyidaw': ['Nay Pyi Taw'],
  'sri-lanka-sri-jayawardenepura-kotte': ['Sri Jayawardenapura Kotte'],
  'palestine-east-jerusalem': ['East Jerusalem'],
}

const CAPITAL_ROLE_BY_ID: Readonly<Record<string, CapitalRole>> = {
  'bolivia-sucre': 'official',
  'bolivia-la-paz': 'seat-of-government',
  'eswatini-mbabane': 'seat-of-government',
  'eswatini-lobamba': 'legislative',
  'nauru-yaren': 'seat-of-government',
  'south-africa-pretoria': 'seat-of-government',
  'south-africa-cape-town': 'legislative',
  'south-africa-bloemfontein': 'judicial',
  'sri-lanka-sri-jayawardenepura-kotte': 'official',
  'sri-lanka-colombo': 'seat-of-government',
}

const CAPITAL_NOTE_BY_ID: Readonly<Record<string, string>> = {
  'nauru-yaren': '瑙鲁未依法指定正式首都，政府机构主要位于亚伦地区。',
}

/** 将已验收世界时间目录中的首都条目聚合为国家记录。 */
function createWorldCapitalCatalog(): readonly CountryCapitalRecord[] {
  const capitalGroups = new Map<string, typeof WORLD_TIME_BUILTIN_OPTIONS[number][]>()

  for (const option of WORLD_TIME_BUILTIN_OPTIONS) {
    if (!option.isCapital) {
      continue
    }

    const group = capitalGroups.get(option.countryNameEn) ?? []
    group.push(option)
    capitalGroups.set(option.countryNameEn, group)
  }

  return [...capitalGroups.entries()].map(([countryNameEn, options]) => {
    const first = options[0]!
    const iso = COUNTRY_ISO_CODES[countryNameEn]

    if (!iso) {
      throw new Error(`Missing world-capitals ISO code: ${countryNameEn}`)
    }

    return {
      id: `country-${iso.alpha3.toLowerCase()}`,
      nameZh: first.countryName,
      nameEn: countryNameEn,
      aliases: COUNTRY_ALIASES_BY_ALPHA3[iso.alpha3] ?? [],
      isoAlpha2: iso.alpha2,
      isoAlpha3: iso.alpha3,
      region: first.continent,
      capitals: options.map((option) => ({
        id: option.id,
        nameZh: option.cityNameZh,
        nameEn: option.cityNameEn,
        aliases: CAPITAL_ALIASES_BY_ID[option.id] ?? [],
        ...(CAPITAL_ROLE_BY_ID[option.id] ? { role: CAPITAL_ROLE_BY_ID[option.id] } : {}),
        ...(CAPITAL_NOTE_BY_ID[option.id] ? { note: CAPITAL_NOTE_BY_ID[option.id] } : {}),
      })),
    }
  })
}

export const WORLD_CAPITAL_DATASET_METADATA: WorldCapitalDatasetMetadata = {
  id: 'world-capitals-v1',
  name: '各国首都参考目录',
  version: 'world-capitals-v1',
  checkedAt: '2026-09-17',
  coverage: '193 个联合国会员国与 2 个非会员永久观察员，共 195 个国家/实体记录；包含 200 条首都条目。',
  validation: '使用已验收世界时间首都目录作为基础，检查国家/首都唯一标识、ISO alpha-2/3、六洲分类、别名、多个首都和例外角色。',
  countryCount: 195,
  capitalCount: 200,
  sources: [
    {
      name: '联合国会员国',
      url: 'https://www.un.org/about-us/member-states',
      scope: '193 个联合国会员国的范围核对。',
      citation: '仅引用成员范围和公开页面信息，不复制页面全文。',
    },
    {
      name: '联合国永久观察员',
      url: 'https://www.un.org/en/about-us/about-permanent-observers',
      scope: '非会员永久观察员的范围核对。',
      citation: '观察员独立标记，不表述为联合国会员国。',
    },
    {
      name: 'UNGEGN World Geographical Names',
      url: 'https://unstats.un.org/unsd/geoinfo/geonames/About.htm',
      scope: '国家、首都和本地/英文名称的交叉核对。',
      citation: '用于名称、首都和必要别名的静态数据复核。',
    },
    {
      name: 'UN M49',
      url: 'https://unstats.un.org/unsd/methodology/m49/',
      scope: '六洲地区标签的数据核对参考。',
      citation: '地理分类仅用于查询，不表达政治归属或承认。',
    },
    {
      name: '美国国务院 Independent States in the World',
      url: 'https://fam.state.gov/FAM/05FAH01/05FAH011020.html',
      scope: '英文短名、正式名和首都的第二来源交叉核对。',
      citation: '仅作为静态数据交叉核对来源，不在运行时请求。',
    },
  ],
}

export const WORLD_CAPITAL_CATALOG: readonly CountryCapitalRecord[] = createWorldCapitalCatalog()
