import type { WorldTimeOption } from './world-time'

/** 世界时间目录支持的洲筛选值。 */
export type WorldTimeContinent = '亚洲' | '欧洲' | '非洲' | '北美洲' | '南美洲' | '大洋洲'

/** 世界时间内置目录中单个城市或首都的完整展示信息。 */
export interface WorldTimeBuiltinOption extends WorldTimeOption {
  readonly cityNameZh: string
  readonly cityNameEn: string
  readonly countryName: string
  readonly countryNameEn: string
  readonly continent: WorldTimeContinent
  readonly isCapital: boolean
}

interface WorldTimeBuiltinRecord {
  readonly id: string
  readonly cityNameZh: string
  readonly cityNameEn: string
  readonly countryName: string
  readonly countryNameEn: string
  readonly timeZone: string
  readonly continent: WorldTimeContinent
  readonly isCapital: boolean
}

const WORLD_TIME_BUILTIN_RECORDS: readonly WorldTimeBuiltinRecord[] = [
  { id: 'afghanistan-kabul', cityNameZh: '喀布尔', cityNameEn: 'Kabul', countryName: '阿富汗', countryNameEn: 'Afghanistan', timeZone: 'Asia/Kabul', continent: '亚洲', isCapital: true },
  { id: 'albania-tirana', cityNameZh: '地拉那', cityNameEn: 'Tirana', countryName: '阿尔巴尼亚', countryNameEn: 'Albania', timeZone: 'Europe/Tirane', continent: '欧洲', isCapital: true },
  { id: 'algeria-algiers', cityNameZh: '阿尔及尔', cityNameEn: 'Algiers', countryName: '阿尔及利亚', countryNameEn: 'Algeria', timeZone: 'Africa/Algiers', continent: '非洲', isCapital: true },
  { id: 'andorra-andorra-la-vella', cityNameZh: '安道尔城', cityNameEn: 'Andorra la Vella', countryName: '安道尔', countryNameEn: 'Andorra', timeZone: 'Europe/Andorra', continent: '欧洲', isCapital: true },
  { id: 'angola-luanda', cityNameZh: '罗安达', cityNameEn: 'Luanda', countryName: '安哥拉', countryNameEn: 'Angola', timeZone: 'Africa/Luanda', continent: '非洲', isCapital: true },
  { id: 'antigua-and-barbuda-saint-johns', cityNameZh: '圣约翰', cityNameEn: 'Saint Johns', countryName: '安提瓜和巴布达', countryNameEn: 'Antigua and Barbuda', timeZone: 'America/Antigua', continent: '北美洲', isCapital: true },
  { id: 'argentina-buenos-aires', cityNameZh: '布宜诺斯艾利斯', cityNameEn: 'Buenos Aires', countryName: '阿根廷', countryNameEn: 'Argentina', timeZone: 'America/Argentina/Buenos_Aires', continent: '南美洲', isCapital: true },
  { id: 'armenia-yerevan', cityNameZh: '埃里温', cityNameEn: 'Yerevan', countryName: '亚美尼亚', countryNameEn: 'Armenia', timeZone: 'Asia/Yerevan', continent: '亚洲', isCapital: true },
  { id: 'australia-canberra', cityNameZh: '堪培拉', cityNameEn: 'Canberra', countryName: '澳大利亚', countryNameEn: 'Australia', timeZone: 'Australia/Canberra', continent: '大洋洲', isCapital: true },
  { id: 'australia-sydney', cityNameZh: '悉尼', cityNameEn: 'Sydney', countryName: '澳大利亚', countryNameEn: 'Australia', timeZone: 'Australia/Sydney', continent: '大洋洲', isCapital: false },
  { id: 'austria-vienna', cityNameZh: '维也纳', cityNameEn: 'Vienna', countryName: '奥地利', countryNameEn: 'Austria', timeZone: 'Europe/Vienna', continent: '欧洲', isCapital: true },
  { id: 'azerbaijan-baku', cityNameZh: '巴库', cityNameEn: 'Baku', countryName: '阿塞拜疆', countryNameEn: 'Azerbaijan', timeZone: 'Asia/Baku', continent: '亚洲', isCapital: true },
  { id: 'bahamas-nassau', cityNameZh: '拿骚', cityNameEn: 'Nassau', countryName: '巴哈马', countryNameEn: 'Bahamas', timeZone: 'America/Nassau', continent: '北美洲', isCapital: true },
  { id: 'bahrain-manama', cityNameZh: '麦纳麦', cityNameEn: 'Manama', countryName: '巴林', countryNameEn: 'Bahrain', timeZone: 'Asia/Bahrain', continent: '亚洲', isCapital: true },
  { id: 'bangladesh-dhaka', cityNameZh: '达卡', cityNameEn: 'Dhaka', countryName: '孟加拉国', countryNameEn: 'Bangladesh', timeZone: 'Asia/Dhaka', continent: '亚洲', isCapital: true },
  { id: 'barbados-bridgetown', cityNameZh: '布里奇敦', cityNameEn: 'Bridgetown', countryName: '巴巴多斯', countryNameEn: 'Barbados', timeZone: 'America/Barbados', continent: '北美洲', isCapital: true },
  { id: 'belarus-minsk', cityNameZh: '明斯克', cityNameEn: 'Minsk', countryName: '白俄罗斯', countryNameEn: 'Belarus', timeZone: 'Europe/Minsk', continent: '欧洲', isCapital: true },
  { id: 'belgium-brussels', cityNameZh: '布鲁塞尔', cityNameEn: 'Brussels', countryName: '比利时', countryNameEn: 'Belgium', timeZone: 'Europe/Brussels', continent: '欧洲', isCapital: true },
  { id: 'belize-belmopan', cityNameZh: '贝尔莫潘', cityNameEn: 'Belmopan', countryName: '伯利兹', countryNameEn: 'Belize', timeZone: 'America/Belize', continent: '北美洲', isCapital: true },
  { id: 'benin-porto-novo', cityNameZh: '波多诺伏', cityNameEn: 'Porto-Novo', countryName: '贝宁', countryNameEn: 'Benin', timeZone: 'Africa/Porto-Novo', continent: '非洲', isCapital: true },
  { id: 'bhutan-thimphu', cityNameZh: '廷布', cityNameEn: 'Thimphu', countryName: '不丹', countryNameEn: 'Bhutan', timeZone: 'Asia/Thimphu', continent: '亚洲', isCapital: true },
  { id: 'bolivia-sucre', cityNameZh: '苏克雷', cityNameEn: 'Sucre', countryName: '玻利维亚', countryNameEn: 'Bolivia', timeZone: 'America/La_Paz', continent: '南美洲', isCapital: true },
  { id: 'bolivia-la-paz', cityNameZh: '拉巴斯', cityNameEn: 'La Paz', countryName: '玻利维亚', countryNameEn: 'Bolivia', timeZone: 'America/La_Paz', continent: '南美洲', isCapital: true },
  { id: 'bosnia-and-herzegovina-sarajevo', cityNameZh: '萨拉热窝', cityNameEn: 'Sarajevo', countryName: '波斯尼亚和黑塞哥维那', countryNameEn: 'Bosnia and Herzegovina', timeZone: 'Europe/Sarajevo', continent: '欧洲', isCapital: true },
  { id: 'botswana-gaborone', cityNameZh: '哈博罗内', cityNameEn: 'Gaborone', countryName: '博茨瓦纳', countryNameEn: 'Botswana', timeZone: 'Africa/Gaborone', continent: '非洲', isCapital: true },
  { id: 'brazil-brasilia', cityNameZh: '巴西利亚', cityNameEn: 'Brasilia', countryName: '巴西', countryNameEn: 'Brazil', timeZone: 'America/Sao_Paulo', continent: '南美洲', isCapital: true },
  { id: 'brunei-bandar-seri-begawan', cityNameZh: '斯里巴加湾市', cityNameEn: 'Bandar Seri Begawan', countryName: '文莱', countryNameEn: 'Brunei', timeZone: 'Asia/Brunei', continent: '亚洲', isCapital: true },
  { id: 'bulgaria-sofia', cityNameZh: '索非亚', cityNameEn: 'Sofia', countryName: '保加利亚', countryNameEn: 'Bulgaria', timeZone: 'Europe/Sofia', continent: '欧洲', isCapital: true },
  { id: 'burkina-faso-ouagadougou', cityNameZh: '瓦加杜古', cityNameEn: 'Ouagadougou', countryName: '布基纳法索', countryNameEn: 'Burkina Faso', timeZone: 'Africa/Ouagadougou', continent: '非洲', isCapital: true },
  { id: 'burundi-gitega', cityNameZh: '基特加', cityNameEn: 'Gitega', countryName: '布隆迪', countryNameEn: 'Burundi', timeZone: 'Africa/Bujumbura', continent: '非洲', isCapital: true },
  { id: 'cabo-verde-praia', cityNameZh: '普拉亚', cityNameEn: 'Praia', countryName: '佛得角', countryNameEn: 'Cabo Verde', timeZone: 'Atlantic/Cape_Verde', continent: '非洲', isCapital: true },
  { id: 'cambodia-phnom-penh', cityNameZh: '金边', cityNameEn: 'Phnom Penh', countryName: '柬埔寨', countryNameEn: 'Cambodia', timeZone: 'Asia/Phnom_Penh', continent: '亚洲', isCapital: true },
  { id: 'cameroon-yaounde', cityNameZh: '雅温得', cityNameEn: 'Yaounde', countryName: '喀麦隆', countryNameEn: 'Cameroon', timeZone: 'Africa/Douala', continent: '非洲', isCapital: true },
  { id: 'canada-ottawa', cityNameZh: '渥太华', cityNameEn: 'Ottawa', countryName: '加拿大', countryNameEn: 'Canada', timeZone: 'America/Toronto', continent: '北美洲', isCapital: true },
  { id: 'central-african-republic-bangui', cityNameZh: '班吉', cityNameEn: 'Bangui', countryName: '中非共和国', countryNameEn: 'Central African Republic', timeZone: 'Africa/Bangui', continent: '非洲', isCapital: true },
  { id: 'chad-ndjamena', cityNameZh: '恩贾梅纳', cityNameEn: "N'Djamena", countryName: '乍得', countryNameEn: 'Chad', timeZone: 'Africa/Ndjamena', continent: '非洲', isCapital: true },
  { id: 'chile-santiago', cityNameZh: '圣地亚哥', cityNameEn: 'Santiago', countryName: '智利', countryNameEn: 'Chile', timeZone: 'America/Santiago', continent: '南美洲', isCapital: true },
  { id: 'china-beijing', cityNameZh: '北京', cityNameEn: 'Beijing', countryName: '中国', countryNameEn: 'China', timeZone: 'Asia/Shanghai', continent: '亚洲', isCapital: true },
  { id: 'colombia-bogota', cityNameZh: '波哥大', cityNameEn: 'Bogota', countryName: '哥伦比亚', countryNameEn: 'Colombia', timeZone: 'America/Bogota', continent: '南美洲', isCapital: true },
  { id: 'comoros-moroni', cityNameZh: '莫罗尼', cityNameEn: 'Moroni', countryName: '科摩罗', countryNameEn: 'Comoros', timeZone: 'Indian/Comoro', continent: '非洲', isCapital: true },
  { id: 'congo-brazzaville', cityNameZh: '布拉柴维尔', cityNameEn: 'Brazzaville', countryName: '刚果共和国', countryNameEn: 'Republic of the Congo', timeZone: 'Africa/Brazzaville', continent: '非洲', isCapital: true },
  { id: 'costa-rica-san-jose', cityNameZh: '圣何塞', cityNameEn: 'San Jose', countryName: '哥斯达黎加', countryNameEn: 'Costa Rica', timeZone: 'America/Costa_Rica', continent: '北美洲', isCapital: true },
  { id: 'cote-divoire-yamoussoukro', cityNameZh: '亚穆苏克罗', cityNameEn: 'Yamoussoukro', countryName: '科特迪瓦', countryNameEn: "Cote d'Ivoire", timeZone: 'Africa/Abidjan', continent: '非洲', isCapital: true },
  { id: 'croatia-zagreb', cityNameZh: '萨格勒布', cityNameEn: 'Zagreb', countryName: '克罗地亚', countryNameEn: 'Croatia', timeZone: 'Europe/Zagreb', continent: '欧洲', isCapital: true },
  { id: 'cuba-havana', cityNameZh: '哈瓦那', cityNameEn: 'Havana', countryName: '古巴', countryNameEn: 'Cuba', timeZone: 'America/Havana', continent: '北美洲', isCapital: true },
  { id: 'cyprus-nicosia', cityNameZh: '尼科西亚', cityNameEn: 'Nicosia', countryName: '塞浦路斯', countryNameEn: 'Cyprus', timeZone: 'Asia/Nicosia', continent: '亚洲', isCapital: true },
  { id: 'czechia-prague', cityNameZh: '布拉格', cityNameEn: 'Prague', countryName: '捷克', countryNameEn: 'Czechia', timeZone: 'Europe/Prague', continent: '欧洲', isCapital: true },
  { id: 'north-korea-pyongyang', cityNameZh: '平壤', cityNameEn: 'Pyongyang', countryName: '朝鲜', countryNameEn: 'North Korea', timeZone: 'Asia/Pyongyang', continent: '亚洲', isCapital: true },
  { id: 'democratic-republic-of-congo-kinshasa', cityNameZh: '金沙萨', cityNameEn: 'Kinshasa', countryName: '刚果民主共和国', countryNameEn: 'Democratic Republic of the Congo', timeZone: 'Africa/Kinshasa', continent: '非洲', isCapital: true },
  { id: 'denmark-copenhagen', cityNameZh: '哥本哈根', cityNameEn: 'Copenhagen', countryName: '丹麦', countryNameEn: 'Denmark', timeZone: 'Europe/Copenhagen', continent: '欧洲', isCapital: true },
  { id: 'djibouti-djibouti', cityNameZh: '吉布提市', cityNameEn: 'Djibouti', countryName: '吉布提', countryNameEn: 'Djibouti', timeZone: 'Africa/Djibouti', continent: '非洲', isCapital: true },
  { id: 'dominica-roseau', cityNameZh: '罗索', cityNameEn: 'Roseau', countryName: '多米尼克', countryNameEn: 'Dominica', timeZone: 'America/Dominica', continent: '北美洲', isCapital: true },
  { id: 'dominican-republic-santo-domingo', cityNameZh: '圣多明各', cityNameEn: 'Santo Domingo', countryName: '多米尼加共和国', countryNameEn: 'Dominican Republic', timeZone: 'America/Santo_Domingo', continent: '北美洲', isCapital: true },
  { id: 'ecuador-quito', cityNameZh: '基多', cityNameEn: 'Quito', countryName: '厄瓜多尔', countryNameEn: 'Ecuador', timeZone: 'America/Guayaquil', continent: '南美洲', isCapital: true },
  { id: 'egypt-cairo', cityNameZh: '开罗', cityNameEn: 'Cairo', countryName: '埃及', countryNameEn: 'Egypt', timeZone: 'Africa/Cairo', continent: '非洲', isCapital: true },
  { id: 'el-salvador-san-salvador', cityNameZh: '圣萨尔瓦多', cityNameEn: 'San Salvador', countryName: '萨尔瓦多', countryNameEn: 'El Salvador', timeZone: 'America/El_Salvador', continent: '北美洲', isCapital: true },
  { id: 'equatorial-guinea-malabo', cityNameZh: '马拉博', cityNameEn: 'Malabo', countryName: '赤道几内亚', countryNameEn: 'Equatorial Guinea', timeZone: 'Africa/Malabo', continent: '非洲', isCapital: true },
  { id: 'eritrea-asmara', cityNameZh: '阿斯马拉', cityNameEn: 'Asmara', countryName: '厄立特里亚', countryNameEn: 'Eritrea', timeZone: 'Africa/Asmara', continent: '非洲', isCapital: true },
  { id: 'estonia-tallinn', cityNameZh: '塔林', cityNameEn: 'Tallinn', countryName: '爱沙尼亚', countryNameEn: 'Estonia', timeZone: 'Europe/Tallinn', continent: '欧洲', isCapital: true },
  { id: 'eswatini-mbabane', cityNameZh: '姆巴巴内', cityNameEn: 'Mbabane', countryName: '埃斯瓦蒂尼', countryNameEn: 'Eswatini', timeZone: 'Africa/Mbabane', continent: '非洲', isCapital: true },
  { id: 'eswatini-lobamba', cityNameZh: '洛班巴', cityNameEn: 'Lobamba', countryName: '埃斯瓦蒂尼', countryNameEn: 'Eswatini', timeZone: 'Africa/Mbabane', continent: '非洲', isCapital: true },
  { id: 'ethiopia-addis-ababa', cityNameZh: '亚的斯亚贝巴', cityNameEn: 'Addis Ababa', countryName: '埃塞俄比亚', countryNameEn: 'Ethiopia', timeZone: 'Africa/Addis_Ababa', continent: '非洲', isCapital: true },
  { id: 'fiji-suva', cityNameZh: '苏瓦', cityNameEn: 'Suva', countryName: '斐济', countryNameEn: 'Fiji', timeZone: 'Pacific/Fiji', continent: '大洋洲', isCapital: true },
  { id: 'finland-helsinki', cityNameZh: '赫尔辛基', cityNameEn: 'Helsinki', countryName: '芬兰', countryNameEn: 'Finland', timeZone: 'Europe/Helsinki', continent: '欧洲', isCapital: true },
  { id: 'france-paris', cityNameZh: '巴黎', cityNameEn: 'Paris', countryName: '法国', countryNameEn: 'France', timeZone: 'Europe/Paris', continent: '欧洲', isCapital: true },
  { id: 'gabon-libreville', cityNameZh: '利伯维尔', cityNameEn: 'Libreville', countryName: '加蓬', countryNameEn: 'Gabon', timeZone: 'Africa/Libreville', continent: '非洲', isCapital: true },
  { id: 'gambia-banjul', cityNameZh: '班珠尔', cityNameEn: 'Banjul', countryName: '冈比亚', countryNameEn: 'Gambia', timeZone: 'Africa/Banjul', continent: '非洲', isCapital: true },
  { id: 'georgia-tbilisi', cityNameZh: '第比利斯', cityNameEn: 'Tbilisi', countryName: '格鲁吉亚', countryNameEn: 'Georgia', timeZone: 'Asia/Tbilisi', continent: '亚洲', isCapital: true },
  { id: 'germany-berlin', cityNameZh: '柏林', cityNameEn: 'Berlin', countryName: '德国', countryNameEn: 'Germany', timeZone: 'Europe/Berlin', continent: '欧洲', isCapital: true },
  { id: 'ghana-accra', cityNameZh: '阿克拉', cityNameEn: 'Accra', countryName: '加纳', countryNameEn: 'Ghana', timeZone: 'Africa/Accra', continent: '非洲', isCapital: true },
  { id: 'greece-athens', cityNameZh: '雅典', cityNameEn: 'Athens', countryName: '希腊', countryNameEn: 'Greece', timeZone: 'Europe/Athens', continent: '欧洲', isCapital: true },
  { id: 'grenada-st-georges', cityNameZh: '圣乔治', cityNameEn: 'St. Georges', countryName: '格林纳达', countryNameEn: 'Grenada', timeZone: 'America/Grenada', continent: '北美洲', isCapital: true },
  { id: 'guatemala-guatemala-city', cityNameZh: '危地马拉城', cityNameEn: 'Guatemala City', countryName: '危地马拉', countryNameEn: 'Guatemala', timeZone: 'America/Guatemala', continent: '北美洲', isCapital: true },
  { id: 'guinea-conakry', cityNameZh: '科纳克里', cityNameEn: 'Conakry', countryName: '几内亚', countryNameEn: 'Guinea', timeZone: 'Africa/Conakry', continent: '非洲', isCapital: true },
  { id: 'guinea-bissau-bissau', cityNameZh: '比绍', cityNameEn: 'Bissau', countryName: '几内亚比绍', countryNameEn: 'Guinea-Bissau', timeZone: 'Africa/Bissau', continent: '非洲', isCapital: true },
  { id: 'guyana-georgetown', cityNameZh: '乔治敦', cityNameEn: 'Georgetown', countryName: '圭亚那', countryNameEn: 'Guyana', timeZone: 'America/Guyana', continent: '南美洲', isCapital: true },
  { id: 'haiti-port-au-prince', cityNameZh: '太子港', cityNameEn: 'Port-au-Prince', countryName: '海地', countryNameEn: 'Haiti', timeZone: 'America/Port-au-Prince', continent: '北美洲', isCapital: true },
  { id: 'honduras-tegucigalpa', cityNameZh: '特古西加尔巴', cityNameEn: 'Tegucigalpa', countryName: '洪都拉斯', countryNameEn: 'Honduras', timeZone: 'America/Tegucigalpa', continent: '北美洲', isCapital: true },
  { id: 'hungary-budapest', cityNameZh: '布达佩斯', cityNameEn: 'Budapest', countryName: '匈牙利', countryNameEn: 'Hungary', timeZone: 'Europe/Budapest', continent: '欧洲', isCapital: true },
  { id: 'iceland-reykjavik', cityNameZh: '雷克雅未克', cityNameEn: 'Reykjavik', countryName: '冰岛', countryNameEn: 'Iceland', timeZone: 'Atlantic/Reykjavik', continent: '欧洲', isCapital: true },
  { id: 'india-new-delhi', cityNameZh: '新德里', cityNameEn: 'New Delhi', countryName: '印度', countryNameEn: 'India', timeZone: 'Asia/Kolkata', continent: '亚洲', isCapital: true },
  { id: 'indonesia-jakarta', cityNameZh: '雅加达', cityNameEn: 'Jakarta', countryName: '印度尼西亚', countryNameEn: 'Indonesia', timeZone: 'Asia/Jakarta', continent: '亚洲', isCapital: true },
  { id: 'iran-tehran', cityNameZh: '德黑兰', cityNameEn: 'Tehran', countryName: '伊朗', countryNameEn: 'Iran', timeZone: 'Asia/Tehran', continent: '亚洲', isCapital: true },
  { id: 'iraq-baghdad', cityNameZh: '巴格达', cityNameEn: 'Baghdad', countryName: '伊拉克', countryNameEn: 'Iraq', timeZone: 'Asia/Baghdad', continent: '亚洲', isCapital: true },
  { id: 'ireland-dublin', cityNameZh: '都柏林', cityNameEn: 'Dublin', countryName: '爱尔兰', countryNameEn: 'Ireland', timeZone: 'Europe/Dublin', continent: '欧洲', isCapital: true },
  { id: 'israel-jerusalem', cityNameZh: '耶路撒冷', cityNameEn: 'Jerusalem', countryName: '以色列', countryNameEn: 'Israel', timeZone: 'Asia/Jerusalem', continent: '亚洲', isCapital: true },
  { id: 'italy-rome', cityNameZh: '罗马', cityNameEn: 'Rome', countryName: '意大利', countryNameEn: 'Italy', timeZone: 'Europe/Rome', continent: '欧洲', isCapital: true },
  { id: 'jamaica-kingston', cityNameZh: '金斯敦', cityNameEn: 'Kingston', countryName: '牙买加', countryNameEn: 'Jamaica', timeZone: 'America/Jamaica', continent: '北美洲', isCapital: true },
  { id: 'japan-tokyo', cityNameZh: '东京', cityNameEn: 'Tokyo', countryName: '日本', countryNameEn: 'Japan', timeZone: 'Asia/Tokyo', continent: '亚洲', isCapital: true },
  { id: 'jordan-amman', cityNameZh: '安曼', cityNameEn: 'Amman', countryName: '约旦', countryNameEn: 'Jordan', timeZone: 'Asia/Amman', continent: '亚洲', isCapital: true },
  { id: 'kazakhstan-astana', cityNameZh: '阿斯塔纳', cityNameEn: 'Astana', countryName: '哈萨克斯坦', countryNameEn: 'Kazakhstan', timeZone: 'Asia/Almaty', continent: '亚洲', isCapital: true },
  { id: 'kenya-nairobi', cityNameZh: '内罗毕', cityNameEn: 'Nairobi', countryName: '肯尼亚', countryNameEn: 'Kenya', timeZone: 'Africa/Nairobi', continent: '非洲', isCapital: true },
  { id: 'kiribati-south-tarawa', cityNameZh: '南塔拉瓦', cityNameEn: 'South Tarawa', countryName: '基里巴斯', countryNameEn: 'Kiribati', timeZone: 'Pacific/Tarawa', continent: '大洋洲', isCapital: true },
  { id: 'kuwait-kuwait-city', cityNameZh: '科威特城', cityNameEn: 'Kuwait City', countryName: '科威特', countryNameEn: 'Kuwait', timeZone: 'Asia/Kuwait', continent: '亚洲', isCapital: true },
  { id: 'kyrgyzstan-bishkek', cityNameZh: '比什凯克', cityNameEn: 'Bishkek', countryName: '吉尔吉斯斯坦', countryNameEn: 'Kyrgyzstan', timeZone: 'Asia/Bishkek', continent: '亚洲', isCapital: true },
  { id: 'laos-vientiane', cityNameZh: '万象', cityNameEn: 'Vientiane', countryName: '老挝', countryNameEn: 'Laos', timeZone: 'Asia/Vientiane', continent: '亚洲', isCapital: true },
  { id: 'latvia-riga', cityNameZh: '里加', cityNameEn: 'Riga', countryName: '拉脱维亚', countryNameEn: 'Latvia', timeZone: 'Europe/Riga', continent: '欧洲', isCapital: true },
  { id: 'lebanon-beirut', cityNameZh: '贝鲁特', cityNameEn: 'Beirut', countryName: '黎巴嫩', countryNameEn: 'Lebanon', timeZone: 'Asia/Beirut', continent: '亚洲', isCapital: true },
  { id: 'lesotho-maseru', cityNameZh: '马塞卢', cityNameEn: 'Maseru', countryName: '莱索托', countryNameEn: 'Lesotho', timeZone: 'Africa/Maseru', continent: '非洲', isCapital: true },
  { id: 'liberia-monrovia', cityNameZh: '蒙罗维亚', cityNameEn: 'Monrovia', countryName: '利比里亚', countryNameEn: 'Liberia', timeZone: 'Africa/Monrovia', continent: '非洲', isCapital: true },
  { id: 'libya-tripoli', cityNameZh: '的黎波里', cityNameEn: 'Tripoli', countryName: '利比亚', countryNameEn: 'Libya', timeZone: 'Africa/Tripoli', continent: '非洲', isCapital: true },
  { id: 'liechtenstein-vaduz', cityNameZh: '瓦杜兹', cityNameEn: 'Vaduz', countryName: '列支敦士登', countryNameEn: 'Liechtenstein', timeZone: 'Europe/Vaduz', continent: '欧洲', isCapital: true },
  { id: 'lithuania-vilnius', cityNameZh: '维尔纽斯', cityNameEn: 'Vilnius', countryName: '立陶宛', countryNameEn: 'Lithuania', timeZone: 'Europe/Vilnius', continent: '欧洲', isCapital: true },
  { id: 'luxembourg-luxembourg', cityNameZh: '卢森堡', cityNameEn: 'Luxembourg', countryName: '卢森堡', countryNameEn: 'Luxembourg', timeZone: 'Europe/Luxembourg', continent: '欧洲', isCapital: true },
  { id: 'madagascar-antananarivo', cityNameZh: '塔那那利佛', cityNameEn: 'Antananarivo', countryName: '马达加斯加', countryNameEn: 'Madagascar', timeZone: 'Indian/Antananarivo', continent: '非洲', isCapital: true },
  { id: 'malawi-lilongwe', cityNameZh: '利隆圭', cityNameEn: 'Lilongwe', countryName: '马拉维', countryNameEn: 'Malawi', timeZone: 'Africa/Blantyre', continent: '非洲', isCapital: true },
  { id: 'malaysia-kuala-lumpur', cityNameZh: '吉隆坡', cityNameEn: 'Kuala Lumpur', countryName: '马来西亚', countryNameEn: 'Malaysia', timeZone: 'Asia/Kuala_Lumpur', continent: '亚洲', isCapital: true },
  { id: 'maldives-male', cityNameZh: '马累', cityNameEn: 'Male', countryName: '马尔代夫', countryNameEn: 'Maldives', timeZone: 'Indian/Maldives', continent: '亚洲', isCapital: true },
  { id: 'mali-bamako', cityNameZh: '巴马科', cityNameEn: 'Bamako', countryName: '马里', countryNameEn: 'Mali', timeZone: 'Africa/Bamako', continent: '非洲', isCapital: true },
  { id: 'malta-valletta', cityNameZh: '瓦莱塔', cityNameEn: 'Valletta', countryName: '马耳他', countryNameEn: 'Malta', timeZone: 'Europe/Malta', continent: '欧洲', isCapital: true },
  { id: 'marshall-islands-majuro', cityNameZh: '马朱罗', cityNameEn: 'Majuro', countryName: '马绍尔群岛', countryNameEn: 'Marshall Islands', timeZone: 'Pacific/Majuro', continent: '大洋洲', isCapital: true },
  { id: 'mauritania-nouakchott', cityNameZh: '努瓦克肖特', cityNameEn: 'Nouakchott', countryName: '毛里塔尼亚', countryNameEn: 'Mauritania', timeZone: 'Africa/Nouakchott', continent: '非洲', isCapital: true },
  { id: 'mauritius-port-louis', cityNameZh: '路易港', cityNameEn: 'Port Louis', countryName: '毛里求斯', countryNameEn: 'Mauritius', timeZone: 'Indian/Mauritius', continent: '非洲', isCapital: true },
  { id: 'mexico-mexico-city', cityNameZh: '墨西哥城', cityNameEn: 'Mexico City', countryName: '墨西哥', countryNameEn: 'Mexico', timeZone: 'America/Mexico_City', continent: '北美洲', isCapital: true },
  { id: 'micronesia-palikir', cityNameZh: '帕利基尔', cityNameEn: 'Palikir', countryName: '密克罗尼西亚联邦', countryNameEn: 'Micronesia', timeZone: 'Pacific/Pohnpei', continent: '大洋洲', isCapital: true },
  { id: 'moldova-chisinau', cityNameZh: '基希讷乌', cityNameEn: 'Chisinau', countryName: '摩尔多瓦', countryNameEn: 'Moldova', timeZone: 'Europe/Chisinau', continent: '欧洲', isCapital: true },
  { id: 'monaco-monaco', cityNameZh: '摩纳哥', cityNameEn: 'Monaco', countryName: '摩纳哥', countryNameEn: 'Monaco', timeZone: 'Europe/Monaco', continent: '欧洲', isCapital: true },
  { id: 'mongolia-ulaanbaatar', cityNameZh: '乌兰巴托', cityNameEn: 'Ulaanbaatar', countryName: '蒙古国', countryNameEn: 'Mongolia', timeZone: 'Asia/Ulaanbaatar', continent: '亚洲', isCapital: true },
  { id: 'montenegro-podgorica', cityNameZh: '波德戈里察', cityNameEn: 'Podgorica', countryName: '黑山', countryNameEn: 'Montenegro', timeZone: 'Europe/Podgorica', continent: '欧洲', isCapital: true },
  { id: 'morocco-rabat', cityNameZh: '拉巴特', cityNameEn: 'Rabat', countryName: '摩洛哥', countryNameEn: 'Morocco', timeZone: 'Africa/Casablanca', continent: '非洲', isCapital: true },
  { id: 'mozambique-maputo', cityNameZh: '马普托', cityNameEn: 'Maputo', countryName: '莫桑比克', countryNameEn: 'Mozambique', timeZone: 'Africa/Maputo', continent: '非洲', isCapital: true },
  { id: 'myanmar-naypyidaw', cityNameZh: '内比都', cityNameEn: 'Naypyidaw', countryName: '缅甸', countryNameEn: 'Myanmar', timeZone: 'Asia/Yangon', continent: '亚洲', isCapital: true },
  { id: 'namibia-windhoek', cityNameZh: '温得和克', cityNameEn: 'Windhoek', countryName: '纳米比亚', countryNameEn: 'Namibia', timeZone: 'Africa/Windhoek', continent: '非洲', isCapital: true },
  { id: 'nauru-yaren', cityNameZh: '亚伦', cityNameEn: 'Yaren', countryName: '瑙鲁', countryNameEn: 'Nauru', timeZone: 'Pacific/Nauru', continent: '大洋洲', isCapital: true },
  { id: 'nepal-kathmandu', cityNameZh: '加德满都', cityNameEn: 'Kathmandu', countryName: '尼泊尔', countryNameEn: 'Nepal', timeZone: 'Asia/Kathmandu', continent: '亚洲', isCapital: true },
  { id: 'netherlands-amsterdam', cityNameZh: '阿姆斯特丹', cityNameEn: 'Amsterdam', countryName: '荷兰', countryNameEn: 'Netherlands', timeZone: 'Europe/Amsterdam', continent: '欧洲', isCapital: true },
  { id: 'new-zealand-wellington', cityNameZh: '惠灵顿', cityNameEn: 'Wellington', countryName: '新西兰', countryNameEn: 'New Zealand', timeZone: 'Pacific/Auckland', continent: '大洋洲', isCapital: true },
  { id: 'nicaragua-managua', cityNameZh: '马那瓜', cityNameEn: 'Managua', countryName: '尼加拉瓜', countryNameEn: 'Nicaragua', timeZone: 'America/Managua', continent: '北美洲', isCapital: true },
  { id: 'niger-niamey', cityNameZh: '尼亚美', cityNameEn: 'Niamey', countryName: '尼日尔', countryNameEn: 'Niger', timeZone: 'Africa/Niamey', continent: '非洲', isCapital: true },
  { id: 'nigeria-abuja', cityNameZh: '阿布贾', cityNameEn: 'Abuja', countryName: '尼日利亚', countryNameEn: 'Nigeria', timeZone: 'Africa/Lagos', continent: '非洲', isCapital: true },
  { id: 'north-macedonia-skopje', cityNameZh: '斯科普里', cityNameEn: 'Skopje', countryName: '北马其顿', countryNameEn: 'North Macedonia', timeZone: 'Europe/Skopje', continent: '欧洲', isCapital: true },
  { id: 'norway-oslo', cityNameZh: '奥斯陆', cityNameEn: 'Oslo', countryName: '挪威', countryNameEn: 'Norway', timeZone: 'Europe/Oslo', continent: '欧洲', isCapital: true },
  { id: 'oman-muscat', cityNameZh: '马斯喀特', cityNameEn: 'Muscat', countryName: '阿曼', countryNameEn: 'Oman', timeZone: 'Asia/Muscat', continent: '亚洲', isCapital: true },
  { id: 'pakistan-islamabad', cityNameZh: '伊斯兰堡', cityNameEn: 'Islamabad', countryName: '巴基斯坦', countryNameEn: 'Pakistan', timeZone: 'Asia/Karachi', continent: '亚洲', isCapital: true },
  { id: 'palau-ngerulmud', cityNameZh: '恩吉鲁穆德', cityNameEn: 'Ngerulmud', countryName: '帕劳', countryNameEn: 'Palau', timeZone: 'Pacific/Palau', continent: '大洋洲', isCapital: true },
  { id: 'panama-panama-city', cityNameZh: '巴拿马城', cityNameEn: 'Panama City', countryName: '巴拿马', countryNameEn: 'Panama', timeZone: 'America/Panama', continent: '北美洲', isCapital: true },
  { id: 'papua-new-guinea-port-moresby', cityNameZh: '莫尔兹比港', cityNameEn: 'Port Moresby', countryName: '巴布亚新几内亚', countryNameEn: 'Papua New Guinea', timeZone: 'Pacific/Port_Moresby', continent: '大洋洲', isCapital: true },
  { id: 'peru-lima', cityNameZh: '利马', cityNameEn: 'Lima', countryName: '秘鲁', countryNameEn: 'Peru', timeZone: 'America/Lima', continent: '南美洲', isCapital: true },
  { id: 'paraguay-asuncion', cityNameZh: '亚松森', cityNameEn: 'Asuncion', countryName: '巴拉圭', countryNameEn: 'Paraguay', timeZone: 'America/Asuncion', continent: '南美洲', isCapital: true },
  { id: 'philippines-manila', cityNameZh: '马尼拉', cityNameEn: 'Manila', countryName: '菲律宾', countryNameEn: 'Philippines', timeZone: 'Asia/Manila', continent: '亚洲', isCapital: true },
  { id: 'poland-warsaw', cityNameZh: '华沙', cityNameEn: 'Warsaw', countryName: '波兰', countryNameEn: 'Poland', timeZone: 'Europe/Warsaw', continent: '欧洲', isCapital: true },
  { id: 'portugal-lisbon', cityNameZh: '里斯本', cityNameEn: 'Lisbon', countryName: '葡萄牙', countryNameEn: 'Portugal', timeZone: 'Europe/Lisbon', continent: '欧洲', isCapital: true },
  { id: 'qatar-doha', cityNameZh: '多哈', cityNameEn: 'Doha', countryName: '卡塔尔', countryNameEn: 'Qatar', timeZone: 'Asia/Qatar', continent: '亚洲', isCapital: true },
  { id: 'south-korea-seoul', cityNameZh: '首尔', cityNameEn: 'Seoul', countryName: '韩国', countryNameEn: 'South Korea', timeZone: 'Asia/Seoul', continent: '亚洲', isCapital: true },
  { id: 'romania-bucharest', cityNameZh: '布加勒斯特', cityNameEn: 'Bucharest', countryName: '罗马尼亚', countryNameEn: 'Romania', timeZone: 'Europe/Bucharest', continent: '欧洲', isCapital: true },
  { id: 'russia-moscow', cityNameZh: '莫斯科', cityNameEn: 'Moscow', countryName: '俄罗斯', countryNameEn: 'Russia', timeZone: 'Europe/Moscow', continent: '欧洲', isCapital: true },
  { id: 'rwanda-kigali', cityNameZh: '基加利', cityNameEn: 'Kigali', countryName: '卢旺达', countryNameEn: 'Rwanda', timeZone: 'Africa/Kigali', continent: '非洲', isCapital: true },
  { id: 'saint-kitts-and-nevis-basseterre', cityNameZh: '巴斯特尔', cityNameEn: 'Basseterre', countryName: '圣基茨和尼维斯', countryNameEn: 'Saint Kitts and Nevis', timeZone: 'America/St_Kitts', continent: '北美洲', isCapital: true },
  { id: 'saint-lucia-castries', cityNameZh: '卡斯特里', cityNameEn: 'Castries', countryName: '圣卢西亚', countryNameEn: 'Saint Lucia', timeZone: 'America/St_Lucia', continent: '北美洲', isCapital: true },
  { id: 'saint-vincent-and-the-grenadines-kingstown', cityNameZh: '金斯敦', cityNameEn: 'Kingstown', countryName: '圣文森特和格林纳丁斯', countryNameEn: 'Saint Vincent and the Grenadines', timeZone: 'America/St_Vincent', continent: '北美洲', isCapital: true },
  { id: 'samoa-apia', cityNameZh: '阿皮亚', cityNameEn: 'Apia', countryName: '萨摩亚', countryNameEn: 'Samoa', timeZone: 'Pacific/Apia', continent: '大洋洲', isCapital: true },
  { id: 'san-marino-san-marino', cityNameZh: '圣马力诺', cityNameEn: 'San Marino', countryName: '圣马力诺', countryNameEn: 'San Marino', timeZone: 'Europe/San_Marino', continent: '欧洲', isCapital: true },
  { id: 'sao-tome-and-principe-sao-tome', cityNameZh: '圣多美', cityNameEn: 'Sao Tome', countryName: '圣多美和普林西比', countryNameEn: 'Sao Tome and Principe', timeZone: 'Africa/Sao_Tome', continent: '非洲', isCapital: true },
  { id: 'saudi-arabia-riyadh', cityNameZh: '利雅得', cityNameEn: 'Riyadh', countryName: '沙特阿拉伯', countryNameEn: 'Saudi Arabia', timeZone: 'Asia/Riyadh', continent: '亚洲', isCapital: true },
  { id: 'senegal-dakar', cityNameZh: '达喀尔', cityNameEn: 'Dakar', countryName: '塞内加尔', countryNameEn: 'Senegal', timeZone: 'Africa/Dakar', continent: '非洲', isCapital: true },
  { id: 'serbia-belgrade', cityNameZh: '贝尔格莱德', cityNameEn: 'Belgrade', countryName: '塞尔维亚', countryNameEn: 'Serbia', timeZone: 'Europe/Belgrade', continent: '欧洲', isCapital: true },
  { id: 'seychelles-victoria', cityNameZh: '维多利亚', cityNameEn: 'Victoria', countryName: '塞舌尔', countryNameEn: 'Seychelles', timeZone: 'Indian/Mahe', continent: '非洲', isCapital: true },
  { id: 'sierra-leone-freetown', cityNameZh: '弗里敦', cityNameEn: 'Freetown', countryName: '塞拉利昂', countryNameEn: 'Sierra Leone', timeZone: 'Africa/Freetown', continent: '非洲', isCapital: true },
  { id: 'singapore-singapore', cityNameZh: '新加坡', cityNameEn: 'Singapore', countryName: '新加坡', countryNameEn: 'Singapore', timeZone: 'Asia/Singapore', continent: '亚洲', isCapital: true },
  { id: 'slovakia-bratislava', cityNameZh: '布拉迪斯拉发', cityNameEn: 'Bratislava', countryName: '斯洛伐克', countryNameEn: 'Slovakia', timeZone: 'Europe/Bratislava', continent: '欧洲', isCapital: true },
  { id: 'slovenia-ljubljana', cityNameZh: '卢布尔雅那', cityNameEn: 'Ljubljana', countryName: '斯洛文尼亚', countryNameEn: 'Slovenia', timeZone: 'Europe/Ljubljana', continent: '欧洲', isCapital: true },
  { id: 'solomon-islands-honiara', cityNameZh: '霍尼亚拉', cityNameEn: 'Honiara', countryName: '所罗门群岛', countryNameEn: 'Solomon Islands', timeZone: 'Pacific/Guadalcanal', continent: '大洋洲', isCapital: true },
  { id: 'somalia-mogadishu', cityNameZh: '摩加迪沙', cityNameEn: 'Mogadishu', countryName: '索马里', countryNameEn: 'Somalia', timeZone: 'Africa/Mogadishu', continent: '非洲', isCapital: true },
  { id: 'south-africa-pretoria', cityNameZh: '比勒陀利亚', cityNameEn: 'Pretoria', countryName: '南非', countryNameEn: 'South Africa', timeZone: 'Africa/Johannesburg', continent: '非洲', isCapital: true },
  { id: 'south-africa-cape-town', cityNameZh: '开普敦', cityNameEn: 'Cape Town', countryName: '南非', countryNameEn: 'South Africa', timeZone: 'Africa/Johannesburg', continent: '非洲', isCapital: true },
  { id: 'south-africa-bloemfontein', cityNameZh: '布隆方丹', cityNameEn: 'Bloemfontein', countryName: '南非', countryNameEn: 'South Africa', timeZone: 'Africa/Johannesburg', continent: '非洲', isCapital: true },
  { id: 'south-sudan-juba', cityNameZh: '朱巴', cityNameEn: 'Juba', countryName: '南苏丹', countryNameEn: 'South Sudan', timeZone: 'Africa/Juba', continent: '非洲', isCapital: true },
  { id: 'spain-madrid', cityNameZh: '马德里', cityNameEn: 'Madrid', countryName: '西班牙', countryNameEn: 'Spain', timeZone: 'Europe/Madrid', continent: '欧洲', isCapital: true },
  { id: 'sri-lanka-sri-jayawardenepura-kotte', cityNameZh: '斯里贾亚瓦德纳普拉科特', cityNameEn: 'Sri Jayawardenepura Kotte', countryName: '斯里兰卡', countryNameEn: 'Sri Lanka', timeZone: 'Asia/Colombo', continent: '亚洲', isCapital: true },
  { id: 'sri-lanka-colombo', cityNameZh: '科伦坡', cityNameEn: 'Colombo', countryName: '斯里兰卡', countryNameEn: 'Sri Lanka', timeZone: 'Asia/Colombo', continent: '亚洲', isCapital: true },
  { id: 'sudan-khartoum', cityNameZh: '喀土穆', cityNameEn: 'Khartoum', countryName: '苏丹', countryNameEn: 'Sudan', timeZone: 'Africa/Khartoum', continent: '非洲', isCapital: true },
  { id: 'suriname-paramaribo', cityNameZh: '帕拉马里博', cityNameEn: 'Paramaribo', countryName: '苏里南', countryNameEn: 'Suriname', timeZone: 'America/Paramaribo', continent: '南美洲', isCapital: true },
  { id: 'sweden-stockholm', cityNameZh: '斯德哥尔摩', cityNameEn: 'Stockholm', countryName: '瑞典', countryNameEn: 'Sweden', timeZone: 'Europe/Stockholm', continent: '欧洲', isCapital: true },
  { id: 'switzerland-bern', cityNameZh: '伯尔尼', cityNameEn: 'Bern', countryName: '瑞士', countryNameEn: 'Switzerland', timeZone: 'Europe/Zurich', continent: '欧洲', isCapital: true },
  { id: 'syria-damascus', cityNameZh: '大马士革', cityNameEn: 'Damascus', countryName: '叙利亚', countryNameEn: 'Syria', timeZone: 'Asia/Damascus', continent: '亚洲', isCapital: true },
  { id: 'tajikistan-dushanbe', cityNameZh: '杜尚别', cityNameEn: 'Dushanbe', countryName: '塔吉克斯坦', countryNameEn: 'Tajikistan', timeZone: 'Asia/Dushanbe', continent: '亚洲', isCapital: true },
  { id: 'tanzania-dodoma', cityNameZh: '多多马', cityNameEn: 'Dodoma', countryName: '坦桑尼亚', countryNameEn: 'Tanzania', timeZone: 'Africa/Dar_es_Salaam', continent: '非洲', isCapital: true },
  { id: 'thailand-bangkok', cityNameZh: '曼谷', cityNameEn: 'Bangkok', countryName: '泰国', countryNameEn: 'Thailand', timeZone: 'Asia/Bangkok', continent: '亚洲', isCapital: true },
  { id: 'timor-leste-dili', cityNameZh: '帝力', cityNameEn: 'Dili', countryName: '东帝汶', countryNameEn: 'Timor-Leste', timeZone: 'Asia/Dili', continent: '亚洲', isCapital: true },
  { id: 'togo-lome', cityNameZh: '洛美', cityNameEn: 'Lome', countryName: '多哥', countryNameEn: 'Togo', timeZone: 'Africa/Lome', continent: '非洲', isCapital: true },
  { id: 'tonga-nukualofa', cityNameZh: '努库阿洛法', cityNameEn: "Nuku'alofa", countryName: '汤加', countryNameEn: 'Tonga', timeZone: 'Pacific/Tongatapu', continent: '大洋洲', isCapital: true },
  { id: 'trinidad-and-tobago-port-of-spain', cityNameZh: '西班牙港', cityNameEn: 'Port of Spain', countryName: '特立尼达和多巴哥', countryNameEn: 'Trinidad and Tobago', timeZone: 'America/Port_of_Spain', continent: '北美洲', isCapital: true },
  { id: 'tunisia-tunis', cityNameZh: '突尼斯', cityNameEn: 'Tunis', countryName: '突尼斯', countryNameEn: 'Tunisia', timeZone: 'Africa/Tunis', continent: '非洲', isCapital: true },
  { id: 'turkey-ankara', cityNameZh: '安卡拉', cityNameEn: 'Ankara', countryName: '土耳其', countryNameEn: 'Turkey', timeZone: 'Europe/Istanbul', continent: '亚洲', isCapital: true },
  { id: 'turkmenistan-ashgabat', cityNameZh: '阿什哈巴德', cityNameEn: 'Ashgabat', countryName: '土库曼斯坦', countryNameEn: 'Turkmenistan', timeZone: 'Asia/Ashgabat', continent: '亚洲', isCapital: true },
  { id: 'tuvalu-funafuti', cityNameZh: '富纳富提', cityNameEn: 'Funafuti', countryName: '图瓦卢', countryNameEn: 'Tuvalu', timeZone: 'Pacific/Funafuti', continent: '大洋洲', isCapital: true },
  { id: 'uganda-kampala', cityNameZh: '坎帕拉', cityNameEn: 'Kampala', countryName: '乌干达', countryNameEn: 'Uganda', timeZone: 'Africa/Kampala', continent: '非洲', isCapital: true },
  { id: 'ukraine-kyiv', cityNameZh: '基辅', cityNameEn: 'Kyiv', countryName: '乌克兰', countryNameEn: 'Ukraine', timeZone: 'Europe/Kyiv', continent: '欧洲', isCapital: true },
  { id: 'united-arab-emirates-abu-dhabi', cityNameZh: '阿布扎比', cityNameEn: 'Abu Dhabi', countryName: '阿拉伯联合酋长国', countryNameEn: 'United Arab Emirates', timeZone: 'Asia/Dubai', continent: '亚洲', isCapital: true },
  { id: 'united-arab-emirates-dubai', cityNameZh: '迪拜', cityNameEn: 'Dubai', countryName: '阿拉伯联合酋长国', countryNameEn: 'United Arab Emirates', timeZone: 'Asia/Dubai', continent: '亚洲', isCapital: false },
  { id: 'united-kingdom-london', cityNameZh: '伦敦', cityNameEn: 'London', countryName: '英国', countryNameEn: 'United Kingdom', timeZone: 'Europe/London', continent: '欧洲', isCapital: true },
  { id: 'united-states-washington-dc', cityNameZh: '华盛顿特区', cityNameEn: 'Washington, D.C.', countryName: '美国', countryNameEn: 'United States', timeZone: 'America/New_York', continent: '北美洲', isCapital: true },
  { id: 'united-states-new-york', cityNameZh: '纽约', cityNameEn: 'New York', countryName: '美国', countryNameEn: 'United States', timeZone: 'America/New_York', continent: '北美洲', isCapital: false },
  { id: 'united-states-los-angeles', cityNameZh: '洛杉矶', cityNameEn: 'Los Angeles', countryName: '美国', countryNameEn: 'United States', timeZone: 'America/Los_Angeles', continent: '北美洲', isCapital: false },
  { id: 'uruguay-montevideo', cityNameZh: '蒙得维的亚', cityNameEn: 'Montevideo', countryName: '乌拉圭', countryNameEn: 'Uruguay', timeZone: 'America/Montevideo', continent: '南美洲', isCapital: true },
  { id: 'uzbekistan-tashkent', cityNameZh: '塔什干', cityNameEn: 'Tashkent', countryName: '乌兹别克斯坦', countryNameEn: 'Uzbekistan', timeZone: 'Asia/Tashkent', continent: '亚洲', isCapital: true },
  { id: 'vanuatu-port-vila', cityNameZh: '维拉港', cityNameEn: 'Port Vila', countryName: '瓦努阿图', countryNameEn: 'Vanuatu', timeZone: 'Pacific/Efate', continent: '大洋洲', isCapital: true },
  { id: 'venezuela-caracas', cityNameZh: '加拉加斯', cityNameEn: 'Caracas', countryName: '委内瑞拉', countryNameEn: 'Venezuela', timeZone: 'America/Caracas', continent: '南美洲', isCapital: true },
  { id: 'vietnam-hanoi', cityNameZh: '河内', cityNameEn: 'Hanoi', countryName: '越南', countryNameEn: 'Vietnam', timeZone: 'Asia/Ho_Chi_Minh', continent: '亚洲', isCapital: true },
  { id: 'holy-see-vatican-city', cityNameZh: '梵蒂冈城', cityNameEn: 'Vatican City', countryName: '梵蒂冈', countryNameEn: 'Holy See', timeZone: 'Europe/Rome', continent: '欧洲', isCapital: true },
  { id: 'palestine-east-jerusalem', cityNameZh: '东耶路撒冷', cityNameEn: 'East Jerusalem', countryName: '巴勒斯坦国', countryNameEn: 'State of Palestine', timeZone: 'Asia/Hebron', continent: '亚洲', isCapital: true },
  { id: 'yemen-sanaa', cityNameZh: '萨那', cityNameEn: "Sanaa", countryName: '也门', countryNameEn: 'Yemen', timeZone: 'Asia/Aden', continent: '亚洲', isCapital: true },
  { id: 'zambia-lusaka', cityNameZh: '卢萨卡', cityNameEn: 'Lusaka', countryName: '赞比亚', countryNameEn: 'Zambia', timeZone: 'Africa/Lusaka', continent: '非洲', isCapital: true },
  { id: 'zimbabwe-harare', cityNameZh: '哈拉雷', cityNameEn: 'Harare', countryName: '津巴布韦', countryNameEn: 'Zimbabwe', timeZone: 'Africa/Harare', continent: '非洲', isCapital: true },
]

/** 将静态目录记录转换为世界时间工具使用的内置选项。 */
function createWorldTimeBuiltinOption(record: WorldTimeBuiltinRecord): WorldTimeBuiltinOption {
  return {
    id: record.id,
    label: record.cityNameZh,
    searchText: [
      record.cityNameZh,
      record.cityNameEn,
      record.countryName,
      record.countryNameEn,
      record.timeZone,
      record.continent,
    ].join(' '),
    timeZone: record.timeZone,
    source: 'builtin',
    cityNameZh: record.cityNameZh,
    cityNameEn: record.cityNameEn,
    countryName: record.countryName,
    countryNameEn: record.countryNameEn,
    continent: record.continent,
    isCapital: record.isCapital,
  }
}

/** 获取世界时间工具的完整静态内置城市与首都目录。 */
export const WORLD_TIME_BUILTIN_OPTIONS: readonly WorldTimeBuiltinOption[] = WORLD_TIME_BUILTIN_RECORDS.map(
  createWorldTimeBuiltinOption,
)
